README.md
src/Promitor.Scraper/Startup.cs

- Provide default configuration when nothing was specified

 Provide default configuration when nothing was specified

---

docs/CNAME
docs/README.md
docs/_config.yml
docs/_layouts/default.html
docs/index.md

Publish documentation on promitor.io

---

docs/index.md

Fix broken link to configuration in promitor.io

Fix broken link to configuration in promitor.io

---

docs/configuration.md
src/Promitor.Scraper/Configuration/EnvironmentVariables.cs
src/Promitor.Scraper/Docs/Open-Api.xml
src/Promitor.Scraper/Extensions/IApplicationBuilderExtensions.cs
src/Promitor.Scraper/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Scraper/Model/Configuration/AzureMetricConfiguration.cs
src/Promitor.Scraper/Model/Configuration/Metrics/MetricDefinition.cs
src/Promitor.Scraper/Scraping/ResouceTypes/ServiceBusQueueScraper.cs
src/Promitor.Scraper/Scraping/ScrapeEndpoint.cs
src/Promitor.Scraper/Startup.cs

Change metrics configuration structure - Configuration Documentation - General improvements

---

docs/configuration/index.md
src/Promitor.Scraper/Configuration/Providers/ScrapeConfigurationProvider.cs
src/Promitor.Scraper/Scraping/ScrapeEndpoint.cs
src/Promitor.Scraper/Validation/Steps/ScrapingScheduleValidationStep.cs

Provide default location for scraping configuration

---

src/Promitor.Scraper.Tests.Unit/Validation/ConfigurationPathValidationStepTests.cs
src/Promitor.Scraper.Tests.Unit/Validation/ScrapingScheduleValidationStepTests.cs
src/Promitor.Scraper/Constants.cs
src/Promitor.Scraper/Validation/Exceptions/ValidationFailedException.cs
src/Promitor.Scraper/Validation/Interfaces/IValidationStep.cs
src/Promitor.Scraper/Validation/Steps/ConfigurationPathValidationStep.cs
src/Promitor.Scraper/Validation/Steps/ScrapingScheduleValidationStep.cs
src/Promitor.Scraper/Validation/Steps/ValidationStep.cs
src/Promitor.Scraper/Validation/ValidationResult.cs
src/Promitor.Scraper/Validation/Validator.cs

Relates to #36
Output in case **validation is valid**:
```
Promitor.Scraper> ██████╗ ██████╗  ██████╗ ███╗   ███╗██╗████████╗ ██████╗ ██████╗ 
Promitor.Scraper> ██╔══██╗██╔══██╗██╔═══██╗████╗ ████║██║╚══██╔══╝██╔═══██╗██╔══██╗
Promitor.Scraper> ██████╔╝██████╔╝██║   ██║██╔████╔██║██║   ██║   ██║   ██║██████╔╝
Promitor.Scraper> ██╔═══╝ ██╔══██╗██║   ██║██║╚██╔╝██║██║   ██║   ██║   ██║██╔══██╗
Promitor.Scraper> ██║     ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║   ██║   ╚██████╔╝██║  ██║
Promitor.Scraper> ╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝
Promitor.Scraper> -------------------------------------------------
Promitor.Scraper> Starting validation of configuration...
Promitor.Scraper> 	Validation step 1/2: Metrics Declaration Path
Promitor.Scraper> 		Scrape configuration …
```

Provide logging about validation results

---

docs/index.md

Add environment variables for Azure Monitor in docs

---

src/Promitor.Scraper/Scraping/ResouceTypes/ServiceBusQueueScraper.cs

Use value instead of ToString()

---

docs/index.md

Update Docker image tag & add known limitations

---

README.md

Update README to trigger new Travis CI Check

---

README.md
docs/README.md
docs/index.md

Add Snyk badge to docs/readme + Align badge styles

---

docs/index.md

Link to license on GitHub

---

docs/thank-you.md

Fix broken links in 'Thank You' page (promitor.io)

---

.travis.yml
src/Promitor.Scraper/Dockerfile

Build Docker image in Travis CI builds

---

src/Promitor.Scraper.Tests.Unit/Validation/AzureAuthenticationValidationStepTests.cs
src/Promitor.Scraper.Tests.Unit/Validation/ConfigurationPathValidationStepTests.cs
src/Promitor.Scraper.Tests.Unit/Validation/MetricsDeclarationValidationStepTests.cs
src/Promitor.Scraper.Tests.Unit/Validation/ScrapingScheduleValidationStepTests.cs
src/Promitor.Scraper/Startup.cs
src/Promitor.Scraper/Validation/Steps/AzureAuthenticationValidationStep.cs

Provide validation for Azure authentication

---

samples/promitor-sample.yaml
src/.dockerignore
src/Promitor.Scraper.Tests.Unit/Builders/MetricsDeclarationBuilder.cs
src/Promitor.Scraper/Configuration/Providers/MetricsDeclarationProvider.cs
src/Promitor.Scraper/Serialization/YamlSerialization.cs
src/Promitor.sln
src/docker-compose.dcproj
src/docker-compose.override.yml
src/docker-compose.yml

Introduce Docker Compose for local testing

---

build/README.md
build/release-promitor-scraper.yaml

Use YAML for build & release

---

deploy/README.md
deploy/kubernetes-spec.yaml
docs/configuration/index.md
docs/configuration/metrics/index.md
docs/configuration/metrics/service-bus-queue.md
docs/deployment/index.md
docs/index.md
docs/thank-you.md

Provide Kubernetes declaration for Promitor

---

src/Promitor.Scraper.Host/Configuration/Providers/Interfaces/IMetricsDeclarationProvider.cs
src/Promitor.Scraper.Host/Configuration/Providers/MetricsDeclarationProvider.cs
src/Promitor.Scraper.Host/Docs/Open-Api.xml
src/Promitor.Scraper.Host/Validation/Steps/MetricsDeclarationValidationStep.cs
src/Promitor.Scraper.Tests.Unit/Promitor.Scraper.Tests.Unit.csproj
src/Promitor.Scraper.Tests.Unit/Serialization/YamlMetricsDeclarationSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Stubs/MetricsDeclarationProviderStub.cs

Provide unit test to serialize & deserialize metrics configuration

---

docs/thank-you.md

Thank xUnit, Bogus & Guard.NET

---

.travis.yml

- Don't build when running tests
- Effectively run the tests, not only list them

Unit testing improvements

---

samples/promitor-sample.yaml
src/Promitor.Scraper.Host/Configuration/Model/Metrics/ResouceTypes/GenericMetricDefinition.cs
src/Promitor.Scraper.Host/Configuration/Model/ResourceType.cs
src/Promitor.Scraper.Host/Configuration/Serialization/MetricsDeserializer.cs
src/Promitor.Scraper.Host/Docs/Open-Api.xml
src/Promitor.Scraper.Host/Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Scraper.Host/Scraping/ResouceTypes/GenericScraper.cs
src/Promitor.Scraper.Host/Scraping/ResouceTypes/ServiceBusQueueScraper.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/MetricsValidator.cs

Provide a first rough version of generic metrics scraping that reads new metrics type from the configuration and scrapes it.
Validation, documentation, etc will be done in follow-up PR.
Relates to #63

Provide first rough version of generic metrics scraping

---

src/Promitor.Scraper.Host/Startup.cs

Enforce enums as string in json serialization

---

renovate.json

Automatically update Microsoft.AspNetCore.App & Docker images.
However, we're turning off image digest pinning, for now.

Automatically update Microsoft.AspNetCore.App & Docker images

---

deploy/kubernetes-spec.yaml
docs/deployment/index.md
docs/index.md

Prepare for v0.2.1 release

---

.github/ISSUE_TEMPLATE/Security_issue.md

Security issue template
Fixes #168 
- Added new template for security issues

Created template for security related report

---

samples/promitor-sample.yaml
src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs
src/Promitor.Scraper.Host/Configuration/Serialization/MetricsDeserializer.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/GenericMetricValidator.cs
src/Promitor.Scraper.Tests.Unit/Validation/Metrics/ResourceTypes/GenericMetricsDeclarationValidationStepTests.cs
src/Promitor.sln

Make generic metric filter optional

---

deploy/kubernetes-spec.yaml
docs/deployment/index.md
docs/index.md

Prepare for v0.3.0 release

---

docs/thank-you.md

VSTS extensions 👉 Azure Pipelines extensions

VSTS extensions 👉 Azure Pipelines extensions

---

docs/index.md
docs/operations/index.md
src/Promitor.Scraper.Host/Controllers/v1/HealthController.cs
src/Promitor.Scraper.Host/Docs/Open-Api.xml
src/Promitor.Scraper.Host/Extensions/IServiceCollectionExtensions.cs

Provide basic health endpoint and fix Swagger UI.
Closes #9

Provide basic health endpoint

---

.travis.yml

Tag Docker image and run it in the CI

Tag Docker image and run it in the CI

---

.travis.yml

Split CI into multiple phases

---

.travis.yml
deploy/kubernetes-spec.yaml
src/Promitor.Scraper.Tests.Unit/Serialization/YamlMetricsDeclarationSerializationTests.cs

Improve code styling as suggested by CodeFactor.

Improve code styling

---

deploy/kubernetes-spec.yaml
docs/deployment/index.md
docs/index.md

Update documentation & deployment samples for release v0.4.0

Update documentation & deployment samples for release v0.4.0

---

docs/configuration/index.md

Docs - Provide links on how to create Azure AD app & get info

---

.github/kubevalidator.yaml

Provide Kubernetes YAML Validation for our deployment spec.
This will be used by https://github.com/apps/kubevalidator in our PRs

Provide Kubernetes YAML Validation

---

docs/thank-you.md

Mention ImgBot, YAMBURGER & kubevalidator on Thank You
Fixes #261 & #262

Mention ImgBot, YAMBURGER & kubevalidator on Thank You

---

docs/deployment/index.md
docs/index.md

Use latest image tag in documentation

---

src/Promitor.Core.Scraping/Promitor.Core.Scraping.csproj
src/Promitor.Core.Scraping/Scraper.cs

Include timestamp information in metrics by using Prometheus.Client 2.1.0.
Thanks to https://github.com/PrometheusClientNet/Prometheus.Client/issues/18

Include timestamp information in metrics

---

.travis.yml

Align Travis job name with recent changes where Snyk scanning is delegated to GitHub App.

Align Travis job name with recent changes

---

docs/configuration/index.md
src/Promitor.Core.Scraping/Scraper.cs
src/Promitor.Core/Infrastructure/FeatureFlag.cs
src/Promitor.Scraper.Tests.Unit/Infrastructure/FeatureFlagTests.cs

Provide capability to opt-out of metric timestamps.
Closes #290

Provide capability to opt-out of metric timestamps

---

docs/index.md

Fixes missing \ in documentation
- add missing \ into docker example command
-
-

fix missing \

---

docs/thank-you.md

Remove "GitHub Tool" from "Thank You"

Remove "GitHub Tool" from "Thank You"

---

.azure-devops/scraper-ci.yml

Dynamically determine build number depending on PR or not.
Relates to #398

Dynamically determine build number depending on PR or not

---

README.md
docs/index.md

Add Azure Pipelines Badge

---

src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/GenericMetricDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/ServiceBusQueueMetricDefinition.cs
src/Promitor.Core.Scraping/Configuration/Serialization/Deserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/MetricsDeserializer.cs
src/Promitor.Core.Scraping/ResouceTypes/GenericScraper.cs
src/Promitor.Core.Scraping/ResouceTypes/ServiceBusQueueScraper.cs
src/Promitor.Core.Telemetry/RuntimeLogger.cs
src/Promitor.Core/Serialization/Yaml/YamlSerialization.cs
src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs
src/Promitor.Scraper.Host/Extensions/IApplicationBuilderExtensions.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/MetricsValidator.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/GenericMetricValidator.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/ServiceBusQueueMetricValidator.cs
src/Promitor.Scraper.Host/Validation/Steps/AzureAuthenticationValidationStep.cs
src/Promitor.Scraper.Host/Validation/Steps/MetricsDeclarationValidationStep.cs
src/Promitor.Scraper.Host/Validation/Steps/ValidationStep.cs
src/Promitor.Scraper.Host/Validation/ValidationResult.cs
src/Promitor.Scraper.Tests.Unit/Builders/MetricsDeclarationBuilder.cs
src/Promitor.Scraper.Tests.Unit/Infrastructure/FeatureFlagTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithServiceBusQueueYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/YamlSerializationTests.cs

Minor cleanups

---

.azure-devops/bots-scraper-ci-docker-image.yml
deploy/automation/scraper/ci/azuredeploy.json

Provide alert around Docker Hub integration with GitHub PRs
Closes #411

Provide alert around Docker Hub integration with GitHub PRs

---

.azure-devops/bots-scraper-ci-docker-image.yml

Automatically deploy changes to our CI automation for scraper, when it is required

Automatically deploy changes to our CI automation for scraper

---

deploy/automation/scraper/ci/azuredeploy.json

Improve alert description and test CD for tooling

Improve alert description

---

.azure-devops/agents-scraper-release-preview.yaml

Provide YAML spec for preview releases for Promitor.
Relates to #430 & #393

Provide YAML spec for preview releases for Promitor

---

.azure-devops/agents-scraper-release-official.yaml

Determine build number based on release

Determine build number based on release

---

.azure-devops/agents-scraper-release-official.yaml

Build & tag major.minor version for official releases

---

src/Promitor.Core.Scraping/ScrapeEndpoint.cs

Fix issue with custom Prometheus scrape path

---

.azure-devops/docker-hub-bot-for-prs-ci.yml
.azure-devops/scraper-ci.yml

-  Pipelines should trigger on changes to themselves. This lets PRs that change the pipelines trigger tests so it can be confirmed they still work
Before implementing this check security settings re: secrets & if they are available to builds of forks.

Set AzDO pipeline to trigger on PRs that include pipeline changes

---

charts/promitor-scraper/templates/configmap.yaml
charts/promitor-scraper/values.yaml
docs/deployment/index.md

Followup to #473 
- Updates the helm chart to use the new scraping schedule value

Update helm chart to work with new scraping schedule value

---

charts/promitor-scraper/templates/NOTES.txt

- Points prometheus @ a cluster DNS address

Corrected prometheus scraping address

---

README.md
docs/index.md

Provide clarification on support

Provide clarification on support

---

README.md
docs/configuration/metrics/container-instances.md
docs/configuration/metrics/container-registry.md
docs/configuration/metrics/cosmos-db.md
docs/configuration/metrics/generic-azure-resource.md
docs/configuration/metrics/network-interface.md
docs/configuration/metrics/service-bus-queue.md
docs/configuration/metrics/storage-queue.md
docs/configuration/metrics/virtual-machine.md
docs/index.md

- Provide badges indicating which version introduces a specific scraper.
- Align badge button with the current badges
Closes #499

Provide badges indicating which version introduces a specific scraper

---

docs/configuration/metrics/index.md
docs/index.md

Minor documentation restructuring

---

.azure-devops/agents-scraper-release-official.yaml
.azure-devops/agents-scraper-release-preview.yaml

Add section to document breaking changes in release notes.
Fixes #255

Add section to document breaking changes in release notes

---

docs/configuration/metrics/storage-queue.md

Add missing SAS Token in Storage Queue docs.
Closes #515

Add missing SAS Token in Storage Queue docs

---

src/Promitor.Core.Scraping/Configuration/Serialization/Core/AggregationDeserializer.cs

Only log warning when no default aggregation is configured

---

src/Promitor.Scraper.Host/Validation/Steps/MetricsDeclarationValidationStep.cs

Re-introduce log of configured metrics declaration, but sanitized so that Storage SAS token is no longer logged.
Relates to #530

Re-introduce log of configured metrics declaration, but sanitized

---

docs/configuration/metrics/index.md
docs/configuration/metrics/storage-queue.md

Reflect new SAS token configuration for Storage Queues in documentation.
Fixes #514

Reflect new SAS token configuration for Storage Queues in documentation

---

docs/deployment/index.md

Adding support for a public Helm Chart via Azure Container Registry.
Relates to #493

Documentation on our public Helm Chart repo

---

docs/Gemfile.lock

Update Gems for our docs

---

charts/promitor-agent-scraper/templates/deployment.yaml
charts/promitor-agent-scraper/values.yaml

Add 'PROMITOR_LOGGING_MINIMUMLEVEL' to Helm Chart

---

.azure-devops/helm-ci.yml
charts/promitor-agent-scraper/Chart.yaml
charts/promitor-agent-scraper/LICENSE
charts/promitor-agent-scraper/README.md
charts/promitor-agent-scraper/values.yaml
docs/deployment/index.md
docs/index.md

Improve Helm Chart
- License added
- Maintainer
- Use v1.0.0-preview-6
- Introduce Helm CI
- Created a README based on Prometheus - https://github.com/helm/charts/tree/master/stable/prometheus
Relates to #555

Improve Helm Chart

---

.azure-devops/helm-ci.yml
charts/promitor-agent-scraper/templates/deployment.yaml
charts/promitor-agent-scraper/values.yaml

Helm CI - Be strict when linting

Helm CI - Be strict when linting

---

src/metric-config.yaml

Minor metric improvements for local testing

Minor metric improvements for local testing

---

.azure-devops/scraper-ci.yml
charts/promitor-agent-scraper/README.md

- Document list of configuration opportunities in Helm Chart docs
- Requirements
- What it deploys
Closes #555

Document list of configuration opportunities in Helm Chart docs

---

charts/promitor-agent-scraper/templates/NOTES.txt
docs/index.md
docs/walkthrough/helm.md
docs/walkthrough/index.md

Fixes #440 
- Add walkthrough through helm install, outline for rest of walkthrough
- Include how to create SB queue, cluster, etc
- Minor helm chart change - notes.txt output

Walkthrough doc for SB Queue example

---

docs/walkthrough/index.md

Docs - Introduce TOC for walkthrough

---

charts/promitor-agent-scraper/README.md
charts/promitor-agent-scraper/values.yaml

Change ports used in Helm chart

---

docs/thank-you.md

Add "Task list completed" & "triage-new-issues" to Thank you.

---

.azure-devops/scraper-ci.yml
charts/promitor-agent-scraper/README.md
charts/promitor-agent-scraper/values.yaml
docs/deployment/index.md
docs/index.md

Change dependencies to 1.0.0-preview-7

Change dependencies to 1.0.0-preview-7

---

docs/configuration/metrics/index.md
docs/configuration/metrics/postgresql.md
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/PostgreSqlMetricDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/ResourceType.cs
src/Promitor.Core.Scraping/Configuration/Serialization/Deserializers/PostgreSqlMetricDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricDeserializerFactory.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/PostgreSqlScraper.cs
src/Promitor.Scraper.Host/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/PostgreSqlMetricValidator.cs
src/Promitor.Scraper.Tests.Unit/Builders/MetricsDeclarationBuilder.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithPostgreSqlYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Validation/Metrics/ResourceTypes/PostgreSqlMetricsDeclarationValidationStepTests.cs

Support for Azure Database for PostgreSQL resource type

---

.azure-devops/scraper-ci.yml

Helm CI - Fix bad repository replacement and update Chart docs

---

.azure-devops/scraper-ci.yml

Make sure to use the correct image version in CI Helm Chart

Make sure to use the correct image version in CI Helm Chart

---

.azure-devops/scraper-ci.yml
build/helm/CI/Package-Chart.ps1
build/helm/CI/Transform-Chart.ps1

- Split build, test, code quality in 3 stages while only building once
- Move Helm chart transformation & pushing to script

Improve our current CI

---

build/azure-devops/scraper-ci.yml
src/Promitor.Scraper.Tests.Unit/Promitor.Scraper.Tests.Unit.csproj

Mark tests as test project for CI to run them

Mark tests as test project for CI to run them

---

src/Promitor.Scraper.Host/Controllers/v1/ConfigurationController.cs
src/Promitor.Scraper.Host/Docs/Open-Api.xml

Provide API endpoint for getting runtime configuration

---

src/Promitor.Core.Configuration/Defaults.cs

Turn off Application Insights by default

Turn off Application Insights by default

---

src/Promitor.Core.Scraping/ScrapeResult.cs

Provide decent ToString for ScrapeResult to improve logging

Provide decent ToString for ScrapeResult to improve logging

---

docs/configuration/v0.x/metrics/index.md

Only list scrapers that are supported in v0.x

[Docs] Only list scrapers that are supported in v0.x

---

src/Promitor.Scraper.Host/Controllers/v1/ConfigurationController.cs
src/Promitor.Scraper.Host/Docs/Open-Api.xml
src/Promitor.Scraper.Host/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Scraper.Host/Extensions/ObjectExtensions.cs

 Sanitize instrumentation key in config endpoint

---

docs/index.md

Fix broken link to scraper overview

[Docs] Fix broken link to scraper overview

---

docs/Gemfile.lock

[Docs] Update bundler to 2.0.2

[Docs] Update bundler to 2.0.2

---

build/azure-devops/agents-scraper-release-preview.yml

Build change log on last release, not last full release to avoid duplicate features that were shipped in previous releases already.

[Preview Release] Build change log on last release, not last full release

---

build/azure-devops/scraper-ci.yml

Provide "experimental" tag that represents the latest of master which is pushed to GitHub Package Registry.
Relates to #693

Provide "experimental" tag representing latest of master in GitHub Package Registry

---

build/azure-devops/scraper-ci.yml

Tag & push PR image to GitHub package registry
Relates to #648

Tag & push PR image to GitHub package registry

---

build/azure-devops/agents-scraper-release-official-helm.yml

Provide release pipeline for Helm chart

---

build/azure-devops/agents-scraper-release-official-helm.yml

Change build number format for Helm charts

---

build/azure-devops/agents-scraper-release-official-helm.yml
charts/promitor-agent-scraper/README.md

Relates to #728 
- List Kubernetes version in Chart README
- Provide GitHub title
- Tweak git tag

Streamline Helm chart release

---

build/azure-devops/scraper-ci.yml

Don't tag with PR if it's not a PR

CI - Don't tag with PR if it's not a PR

---

build/azure-devops/agents-scraper-release-official-helm.yml
charts/promitor-agent-scraper/README.md

Relates to #728 
- Fix broken link
- Include custom release notes
- Remove automatic diff based on commits

Improve GitHub release for Helm charts

---

build/azure-devops/scraper-ci.yml

Build - Migrate to Resharper CLI v2.0 Task

Build - Migrate to Resharper CLI v2.0 Task

---

build/azure-devops/agents-scraper-release-official.yml
build/azure-devops/agents-scraper-release-preview.yml

GitHub - Use issue-based change log

---

docs/metrics/labels.md

@tomkerkhove ironically I had already fixed this a second before you merged the other PR 🙈

Sorting resource names alphabetically

---

docs/configuration/v1.x/metrics/azure-sql-database.md

Fix incorrect Azure SQL DB example in docs
Follow-up for #748

Docs - Fix incorrect Azure SQL DB example

---

src/metric-config.yaml

Include Azure SQL DB as local resource

DEV: Include Azure SQL DB as local resource

---

docs/configuration/v1.x/metrics/index.md
docs/configuration/v1.x/metrics/sql-database.md
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/SqlDatabaseResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/ResourceType.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureResourceDeserializerFactory.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Mapping/V1MappingProfile.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/ResourceTypes/SqlDatabaseResourceV1.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/SqlDatabaseDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/SqlDatabaseScraper.cs
src/Promitor.Scraper.Host/Docs/Open-Api.xml
src/Promitor.Scraper.Host/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/SqlDatabaseMetricValidator.cs
src/Promitor.Scraper.Tests.Unit/Builders/Metrics/v1/MetricsDeclarationBuilder.cs
src/Promitor.Scraper.Tests.Unit/Serialization/v1/Providers/SqlDatabaseDeserializerTests.cs
src/Promitor.Scraper.Tests.Unit/Validation/Metrics/ResourceTypes/SqlDatabaseMetricsDeclarationValidationStepTests.cs

Rename 'AzureSqlDatabase' scraper to 'SqlDatabase' 

---

build/azure-devops/scraper-ci.yml

Remove documentation linting for now

---

SUPPORT.md

Fix doc linting in SUPPORT.md

---

adding-a-new-scraper.md
changelog/content/experimental/unreleased.md
docs/configuration/v1.x/metrics/index.md
docs/configuration/v1.x/metrics/sql-managed-instance.md
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/SqlManagedInstanceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/ResourceType.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureResourceDeserializerFactory.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Mapping/V1MappingProfile.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/ResourceTypes/SqlManagedInstanceResourceV1.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/SqlManagedInstanceDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/SqlManagedInstanceScraper.cs
src/Promitor.Scraper.Host/Docs/Open-Api.xml
src/Promitor.Scraper.Host/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/SqlManagedInstanceMetricValidator.cs
src/Promitor.Scraper.Tests.Unit/Builders/Metrics/v1/MetricsDeclarationBuilder.cs
src/Promitor.Scraper.Tests.Unit/Serialization/v1/Providers/SqlManagedInstanceDeserializerTests.cs
src/Promitor.Scraper.Tests.Unit/Validation/Metrics/ResourceTypes/SqlManagedInstanceMetricsDeclarationValidationStepTests.cs

Provide support for scraping metrics for Azure SQL Managed Instance

---

.markdownlint.json
changelog/content/experimental/unreleased.md
docs/configuration/v1.x/metrics/index.md
docs/faq.md
docs/index.md
src/Promitor.Core.Scraping/Configuration/Model/AzureMetadata.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureMetadataDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/AzureCloudsV1.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/AzureMetadataV1.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs
src/Promitor.Scraper.Tests.Unit/Serialization/v1/Core/AzureMetadataDeserializerTests.cs

Provide support for all Azure clouds 

---

build/azure-devops/agents-scraper-release-official.yml
build/azure-devops/agents-scraper-release-preview.yml
build/azure-devops/scraper-ci.yml
changelog/content/experimental/unreleased.md
src/Promitor.Core.Configuration/Promitor.Core.Configuration.csproj
src/Promitor.Core.Telemetry.Metrics/Promitor.Core.Telemetry.Metrics.csproj
src/Promitor.Integrations.AzureStorage/Promitor.Integrations.AzureStorage.csproj
src/Promitor.Scraper.Host/Dockerfile

Security patch for CVE-2020-0602 & CVE-2020-0603

---

changelog/content/experimental/unreleased.md
src/Promitor.Scraper.Host/Docs/Open-Api.xml
src/Promitor.Scraper.Host/Extensions/IApplicationBuilderExtensions.cs
src/Promitor.Scraper.Host/Promitor.Scraper.Host.csproj
src/Promitor.Scraper.Host/Startup.cs

OpenAPI 3.0 docs & UI are not exposed correctly

---

changelog/content/experimental/unreleased.md
charts/promitor-agent-scraper/README.md
charts/promitor-agent-scraper/templates/service.yaml
charts/promitor-agent-scraper/values.yaml

Fixes https://github.com/tomkerkhove/promitor/issues/861

Support Prometheus service discovery with Kubernetes annotations

---

src/Promitor.Core.Scraping/Configuration/Serialization/ConfigurationSerializer.cs
src/Promitor.Core.Scraping/Scraper.cs

Fix code quality

---

docs/configuration/v1.x/metrics/function-app.md

Document optional slotName field for Azure Function App

---

src/Promitor.Scraper.Host/Dockerfile

Update Docker image dependencies

---

build/azure-devops/docs-ci.yml
build/azure-devops/scraper-ci.yml

Provide seperate documentation CI

---

src/Promitor.Core.Scraping/Promitor.Core.Scraping.csproj
src/Promitor.Scraper.Host/Extensions/IApplicationBuilderExtensions.cs

Use upstream Swashbuckle feature introduced in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1481

Use upstream Swashbuckle feature

---

docs/deployment/index.md
docs/index.md

Docs - Update image version & update deployment docs

---

build/azure-devops/scraper-ci.yml

Fix CI to work well with non-PR builds

---

build/azure-devops/scraper-ci.yml

Windows doesn't seem to work on GitHub Package Registry.
Fixes #914

Remove experimental container for Windows

---

src/docker-compose.yml

Run Grafana & Graphite locally via Docker Compose

---

changelog/content/experimental/unreleased.md
docs/configuration/v1.x/metrics/index.md

Provide docs for upcoming default metric labels

---

src/Promitor.Agents.ResourceDiscovery/Graph/Authentication.cs
src/Promitor.Agents.ResourceDiscovery/Health/AzureResourceGraphHealthCheck.cs
src/Promitor.Agents.Scraper/Program.cs
src/Promitor.Agents.Scraper/Startup.cs
src/Promitor.Agents.Scraper/Validation/RuntimeValidator.cs
src/Promitor.Agents.Scraper/Validation/Steps/Sinks/StatsDMetricSinkValidationStep.cs
src/Promitor.Tests.Unit/Configuration/RuntimeConfigurationUnitTest.cs
src/Promitor.Tests.Unit/Generators/Config/BogusRuntimeConfigurationGenerator.cs
src/Promitor.Tests.Unit/Generators/Config/RuntimeConfigurationGenerator.cs
src/Promitor.Tests.Unit/Validation/Metrics/Sinks/StatsDMetricSinkValidationStepTests.cs

Provide sink validation for StatsD

---

README.md
docs/_config.yml
docs/configuration/v1.x/metrics/index.md
docs/configuration/v1.x/runtime.md
docs/index.md

Promitor - Bringing Azure Monitor metrics where you need them

---

config/prometheus/prometheus.yml
src/docker-compose.yml
src/runtime-config.yaml

Configure Prometheus locally in Docker Compose

---

changelog/content/experimental/unreleased.md
docs/configuration/v1.x/metrics/index.md
docs/configuration/v1.x/metrics/key-vault.md
src/Promitor.Agents.Scraper/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Agents.Scraper/Validation/MetricDefinitions/ResourceTypes/KeyVaultMetricValidator.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/KeyVaultResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/ResourceType.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureResourceDeserializerFactory.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Mapping/V1MappingProfile.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/ResourceTypes/KeyVaultResourceV1.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/KeyVaultDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/KeyVaultScraper.cs
src/Promitor.Tests.Unit/Builders/Metrics/v1/MetricsDeclarationBuilder.cs
src/Promitor.Tests.Unit/Serialization/v1/Providers/KeyVaultDeserializerTests.cs
src/Promitor.Tests.Unit/Validation/Metrics/ResourceTypes/KeyVaultMetricsDeclarationValidationStepsTests.cs

Provide support for scraping Azure Key Vault

---

changelog/content/experimental/unreleased.md

Document patch for CVE-2020-1161

---

changelog/content/released/v1.6.0.md

Publish changelog for v1.6.0 release

Publish changelog for v1.6.0 release

---

build/azure-devops/agents-ci-discovery.yml
build/azure-devops/agents-ci-scraper.yml

Remove GitHub Package registry for CIs

---

config/promitor/scraper/runtime.yaml
src/Promitor.Agents.Core/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Agents.Core/Serialization/HealthReportEntryConverter.cs
src/Promitor.Agents.Scraper/Configuration/ResourceDiscoveryConfiguration.cs
src/Promitor.Agents.Scraper/Configuration/ScraperRuntimeConfiguration.cs
src/Promitor.Agents.Scraper/Discovery/ResourceDiscoveryClient.cs
src/Promitor.Agents.Scraper/Discovery/ResourceDiscoveryRepository.cs
src/Promitor.Agents.Scraper/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Agents.Scraper/Health/ResourceDiscoveryHealthCheck.cs
src/Promitor.Agents.Scraper/Startup.cs
src/Promitor.Agents.Scraper/Validation/RuntimeValidator.cs
src/Promitor.Agents.Scraper/Validation/Steps/ResourceDiscoveryValidationStep.cs
src/Promitor.Agents.Scraper/Validation/Steps/Sinks/StatsDMetricSinkValidationStep.cs
src/Promitor.Tests.Unit/Configuration/RuntimeConfigurationUnitTest.cs
src/Promitor.Tests.Unit/Generators/Config/BogusScraperRuntimeConfigurationGenerator.cs
src/Promitor.Tests.Unit/Generators/Config/RuntimeConfigurationGenerator.cs
src/Promitor.Tests.Unit/Validation/Metrics/Sinks/StatsDMetricSinkValidationStepTests.cs
src/Promitor.Tests.Unit/Validation/Misc/ResourceDiscoveryValidationStepTests.cs

Provide configuration & health check for resource discovery integration

---

src/Promitor.Core/Metrics/Sinks/MetricSinkType.cs
src/Promitor.Core/RuntimeMetricNames.cs
src/Promitor.Integrations.Sinks.Prometheus/PrometheusScrapingEndpointMetricSink.cs
src/Promitor.Integrations.Sinks.Prometheus/RuntimeMetricsCollector.cs

Fix ratelimit_arm reported instead of promitor_ratelimit_arm for Prometheus sink

---

changelog/content/experimental/unreleased.md
changelog/content/released/v1.6.1.md

Provide changelog for v1.6.1

---

src/Promitor.Agents.ResourceDiscovery/Docs/Open-Api.xml
src/Promitor.Agents.ResourceDiscovery/Graph/AzureResourceGraph.cs
src/Promitor.Agents.ResourceDiscovery/Repositories/ResourceRepository.cs

Provide dependency tracking for Azure Resource Graph and report metric for amount of found resources per collection.
Fixes #970

Dependency tracking graph

---

charts/promitor-agent-scraper/README.md
charts/promitor-agent-scraper/templates/configmap.yaml
charts/promitor-agent-scraper/values.yaml

Provide capability to configure resource discovery with Helm chart

---

changelog/content/deprecated/prometheus-legacy-configuration.md
changelog/content/deprecated/swagger-2.0.md
changelog/content/deprecated/swagger-ui-2.0.md

Improve deprecation dates on changelog.promitor.io.

Improve deprecation dates on changelog.promitor.io

---

config/promitor/scraper/metrics.yaml
src/Promitor.Agents.Scraper/Docs/Open-Api.xml
src/Promitor.Agents.Scraper/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Agents.Scraper/Scheduling/MetricScrapingJob.cs
src/Promitor.Agents.Scraper/Scheduling/ResourceCollectionScrapingJob.cs
src/Promitor.Agents.Scraper/Scheduling/ResourceScrapingJob.cs
src/Promitor.Agents.Scraper/Scheduling/SchedulingExtensions.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/MetricDefinition.cs
src/Promitor.Integrations.AzureMonitor/RequestHandlers/AzureResourceManagerThrottlingRequestHandler.cs

Schedule job per resource collection and discover resources for the collection name
Relates to #512

Schedule job per resource collection and discover resources for the collection name

---

config/promitor/scraper/metrics.yaml

Fix bad collection name

---

changelog/content/experimental/unreleased.md
src/Promitor.Agents.Scraper/Startup.cs

Remove Swagger (UI) 2.0 support

---

src/Promitor.Tests.Integration/Services/ResourceDiscoveryTests.cs

Align integration tests with new Azure landscape

---

.tours/add-a-new-scraper.tour
.tours/csharp-project-overview.tour
.tours/project-overview.tour
.tours/repo-overview.tour

I've added a few CodeTours to Promitor:
- An overview of the repo.
- A description of the different C# projects.
- A tour explaining how to add a new Scraper.
Fixes #1111

Add a few code tours

---

adding-a-new-scraper.md

Document possibility to use code tour for adding new scrapers

---

.github/workflows/codeql-analysis.yml

Configure code scanning

---

.github/workflows/anchore-analysis.yml

Container Scanning

---

src/Promitor.Agents.ResourceDiscovery/Graph/ResourceDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/AppPlanDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/AppServiceResourceDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/ContainerRegistryDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/FunctionAppDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/LogicAppDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/VirtualMachineDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/VirtualMachineScaleSetDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/WebAppDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Repositories/ResourceRepository.cs

Simplify resource discovery query building to reduce duplication, but still be open

Simplify resource discovery query building to reduce duplication, but still be open

---

config/promitor/resource-discovery/resource-discovery-declaration.yaml
docs/configuration/v2.x/metrics/api-management.md
docs/configuration/v2.x/metrics/container-instances.md
docs/configuration/v2.x/metrics/cosmos-db.md
docs/configuration/v2.x/metrics/iot-hub-device-provisioning-service.md
docs/configuration/v2.x/metrics/iot-hub.md
docs/configuration/v2.x/metrics/key-vault.md
docs/configuration/v2.x/metrics/logic-apps.md
docs/configuration/v2.x/metrics/redis-cache.md
docs/configuration/v2.x/metrics/virtual-machine-scale-set.md
docs/configuration/v2.x/metrics/virtual-machine.md
src/Promitor.Agents.ResourceDiscovery/Graph/Query/GraphQueryBuilder.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceDiscoveryFactory.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/ApiManagementDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/ContainerInstanceDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/CosmosDbDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/DeviceProvisioningServiceDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/IoTHubDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/KeyVaultDiscoveryQuery.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/RedisCacheDiscoveryQuery.cs

Fixes #1118
Fixes #1119
Fixes #1120
Fixes #1121
Fixes #1123
Fixes #1124
Fixes  #1125

Provide resource discovery support for more scrapers

---

docs/index.md
docs/operations/index.md
src/Promitor.Agents.Scraper/Extensions/IHealthChecksBuilderExtensions.cs
src/Promitor.Agents.Scraper/Startup.cs

Provide documentation about resource discovery health check in scraper health endpoint

---

docs/configuration/v2.x/resource-discovery.md
docs/configuration/v2.x/runtime.md
docs/index.md

Provide documentation on how to configure integration with Promitor Resource Discovery agent

---

docs/configuration/v2.x/metrics/event-hubs.md
docs/configuration/v2.x/metrics/index.md
docs/configuration/v2.x/resource-discovery.md
docs/configuration/v2.x/runtime.md
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceDiscoveryFactory.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/EventHubsDiscoveryQuery.cs
src/Promitor.Agents.Scraper/Discovery/ResourceDiscoveryClient.cs
src/Promitor.Agents.Scraper/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Agents.Scraper/Validation/MetricDefinitions/ResourceTypes/EventHubsMetricValidator.cs
src/Promitor.Core.Contracts/ResourceType.cs
src/Promitor.Core.Contracts/ResourceTypes/EventHubResourceDefinition.cs
src/Promitor.Core.Scraping/AzureMonitorScraper.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureResourceDeserializerFactory.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Mapping/V1MappingProfile.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/ResourceTypes/EventHubsResourceV1.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/EventHubsDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/DeviceProvisioningServiceScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/EventHubsScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/IoTHubScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/KeyVaultScraper.cs
src/Promitor.Core.Scraping/Scraper.cs
src/Promitor.Core/Metrics/MeasuredMetric.cs
src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs
src/Promitor.Tests.Unit/Builders/Metrics/v1/MetricsDeclarationBuilder.cs
src/Promitor.Tests.Unit/Serialization/v1/Providers/EventHubsDeserializerTests.cs
src/Promitor.Tests.Unit/Serialization/v1/YamlAssert.cs
src/Promitor.Tests.Unit/Validation/Metrics/ResourceTypes/EventHubsMetricsDeclarationValidationStepTests.cs

Provide Azure Event hubs scraper

---

config/promitor/resource-discovery/resource-discovery-declaration.yaml
config/promitor/scraper/metrics.yaml

Add Azure Event Hubs metric to local config

Add Azure Event Hubs metric to local config

---

build/azure-devops/agents-scraper-release-official.yml

Preview releases should not push `{major}.{minor}` tag

---

src/Promitor.Tests.Integration/Services/ResourceDiscoveryTests.cs

Fix integration tests due to new Azure resources

---

changelog/content/experimental/unreleased.md
config/promitor/scraper/runtime.yaml
src/Promitor.Agents.Scraper/Extensions/IServiceCollectionExtensions.cs

Ensure Prometheus metric sink does write timestamps (#1217)

---

build/azure-devops/agents-ci-discovery.yml
build/azure-devops/agents-ci-scraper.yml
build/azure-devops/agents-scraper-release-official.yml
build/azure-devops/templates/build-docker-image.yml

Stamp version for release

---

build/azure-devops/templates/quality/run-code-quality.yml
build/azure-devops/templates/tests/run-integration-tests.yml
build/azure-devops/templates/tests/run-unit-tests.yml

Use build/install-sdk.yml for all templates

Use build/install-sdk.yml for all templates

---

changelog/content/released/v2.0.0-preview-1.md
changelog/content/released/v2.0.0-preview-2.md

Provide changelog for 2.0.0-preview-1 & 2.0.0-preview-2

---

changelog/content/experimental/unreleased.md
src/Promitor.Agents.Core/AgentProgram.cs
src/Promitor.Agents.ResourceDiscovery/Program.cs
src/Promitor.Agents.Scraper/Program.cs

Show Promitor version during startup

---

changelog/content/released/v2.0.0-preview-3.md

Provide changelog for v2.0.0-preview-3

Provide changelog for v2.0.0-preview-3

---

src/Promitor.Agents.ResourceDiscovery/Dockerfile.linux
src/Promitor.Agents.Scraper/Dockerfile.linux

Use Alpine

---

src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs

Use new test amounts for discovery to reflect Azure landscape

Use new test amounts for discovery to reflect Azure landscape

---

changelog/content/experimental/unreleased.md

Give attribution to @bluepixbe his work

Give attribution to @bluepixbe

---

docs/deployment/index.md

Fix broken link to deployment guidance

---

build/azure-devops/agents-ci-discovery.yml
build/azure-devops/agents-ci-scraper.yml
build/azure-devops/templates/helm/package-preview-chart.yml
build/azure-devops/templates/stages/helm-chart-verification.yml
build/helm/Transform-Chart.ps1

Push CI Helm chart with CI Helm chart name

---

development-guide.md

Provide updated dev guide to include build arg

Provide updated dev guide to include build arg

---

build/azure-devops/agents-ci-discovery.yml
build/azure-devops/templates/build-discovery-image.yml
charts/promitor-agent-resource-discovery/values.yaml
docs/deployment/resource-discovery/index.md
src/docker-compose.yml

Rename `promitor-agent-discovery` image to `promitor-agent-resource-discovery`

---

docs/deployment/resource-discovery/index.md
docs/deployment/scraper/index.md
docs/index.md

Provide documentation for installing Resource Discovery chart

---

build/azure-devops/agents-resource-discovery-release-official.yml
build/azure-devops/agents-scraper-release-official.yml
build/azure-devops/variables/containers.yml
build/azure-devops/variables/helm.yml
src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs

Provide automated release pipeline for Resource Discovery agent

---

docs/configuration/v2.x/metrics/api-management.md
docs/configuration/v2.x/metrics/app-plan.md
docs/configuration/v2.x/metrics/application-gateway.md
docs/configuration/v2.x/metrics/container-instances.md
docs/configuration/v2.x/metrics/container-registry.md
docs/configuration/v2.x/metrics/cosmos-db.md
docs/configuration/v2.x/metrics/event-hubs.md
docs/configuration/v2.x/metrics/express-route-circuit.md
docs/configuration/v2.x/metrics/function-app.md
docs/configuration/v2.x/metrics/iot-hub-device-provisioning-service.md
docs/configuration/v2.x/metrics/iot-hub.md
docs/configuration/v2.x/metrics/key-vault.md
docs/configuration/v2.x/metrics/kubernetes.md
docs/configuration/v2.x/metrics/logic-apps.md
docs/configuration/v2.x/metrics/network-gateway.md
docs/configuration/v2.x/metrics/network-interface.md
docs/configuration/v2.x/metrics/postgresql.md
docs/configuration/v2.x/metrics/redis-cache.md
docs/configuration/v2.x/metrics/service-bus-queue.md
docs/configuration/v2.x/metrics/sql-database.md
docs/configuration/v2.x/metrics/sql-managed-instance.md
docs/configuration/v2.x/metrics/storage-account.md
docs/configuration/v2.x/metrics/virtual-machine-scale-set.md
docs/configuration/v2.x/metrics/virtual-machine.md
docs/configuration/v2.x/metrics/web-app.md

Provide samples to all scrapers that support Resource Discovery

---

src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs

Update expected test results with reality based on my Azure subscription.

Update expected test results with reality

---

build/azure-devops/agents-ci-discovery.yml
changelog/content/experimental/unreleased.md
charts/promitor-agent-resource-discovery/README.md
charts/promitor-agent-resource-discovery/templates/_helpers.tpl
charts/promitor-agent-resource-discovery/templates/configmap.yaml
charts/promitor-agent-resource-discovery/templates/deployment.yaml
charts/promitor-agent-resource-discovery/templates/podsecuritypolicy.yaml
charts/promitor-agent-resource-discovery/templates/role.yaml
charts/promitor-agent-resource-discovery/templates/rolebinding.yaml
charts/promitor-agent-resource-discovery/templates/secret.yaml
charts/promitor-agent-resource-discovery/templates/service.yaml
charts/promitor-agent-resource-discovery/templates/serviceaccount.yaml
charts/promitor-agent-resource-discovery/values.yaml
charts/promitor-agent-scraper/README.md
charts/promitor-agent-scraper/templates/_helpers.tpl
charts/promitor-agent-scraper/templates/configmap.yaml
charts/promitor-agent-scraper/templates/deployment.yaml
charts/promitor-agent-scraper/templates/podsecuritypolicy.yaml
charts/promitor-agent-scraper/templates/role.yaml
charts/promitor-agent-scraper/templates/rolebinding.yaml
charts/promitor-agent-scraper/templates/secret.yaml
charts/promitor-agent-scraper/templates/service.yaml
charts/promitor-agent-scraper/templates/serviceaccount.yaml
charts/promitor-agent-scraper/values.yaml
docs/deployment/resource-discovery/index.md
package-lock.json
package.json

Cleanup Helm chart

---

build/azure-devops/agents-ci-discovery.yml
build/azure-devops/agents-ci-scraper.yml
build/azure-devops/agents-resource-discovery-release-official.yml
build/azure-devops/agents-scraper-release-official-helm.yml
build/azure-devops/agents-scraper-release-official.yml
build/azure-devops/variables/tests.yml
src/Promitor.Tests.Integration/Clients/AgentClient.cs
src/Promitor.Tests.Integration/Clients/ScraperClient.cs
src/Promitor.Tests.Integration/Extensions/HttpResponseHeadersExtensions.cs
src/Promitor.Tests.Integration/Promitor.Tests.Integration.csproj
src/Promitor.Tests.Integration/Services/ResourceDiscovery/HealthTests.cs
src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceCollectionTests.cs
src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs
src/Promitor.Tests.Integration/Services/ResourceDiscovery/SystemTests.cs
src/Promitor.Tests.Integration/Services/Scraper/ConfigurationTests.cs
src/Promitor.Tests.Integration/Services/Scraper/HealthTests.cs
src/Promitor.Tests.Integration/Services/Scraper/MetricSinksTests.cs
src/Promitor.Tests.Integration/appsettings.json

Provide integration tests for other operations

---

src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs

Align test outcome with Azure subscription

Align test outcome with Azure subscription

---

docs/thank-you.md

Thank you [Semantic Pull Requests](https://github.com/zeke/semantic-pull-requests)
Fixes https://github.com/tomkerkhove/promitor/issues/1362

docs: Thank you Semantic Pull Requests

---

build/azure-devops/agents-ci-scraper.yml
changelog/content/deprecated/helm-2.0.md
changelog/content/deprecated/prometheus-legacy-configuration.md
changelog/content/deprecated/swagger-2.0.md
changelog/content/deprecated/swagger-ui-2.0.md
changelog/content/experimental/unreleased.md
docs/faq.md

chore: Remove support for Helm 2

---

src/Promitor.Core.Scraping/Configuration/Model/Metrics/MetricDefinition.cs

chore: Verify if scrape definition is created correctly

---

changelog/content/experimental/unreleased.md
charts/promitor-agent-resource-discovery/README.md
charts/promitor-agent-resource-discovery/templates/service.yaml
charts/promitor-agent-resource-discovery/values.yaml
charts/promitor-agent-scraper/README.md
charts/promitor-agent-scraper/templates/service.yaml
charts/promitor-agent-scraper/values.yaml

Fixes #1398
Fixes #1402
Fixes #1403

feat: Provide support for internal load balancer & fix combination with automatic Prometheus discovery

---

src/Promitor.Agents.Core/AgentStartup.cs
src/Promitor.Agents.Scraper/Docs/Open-Api.xml
src/Promitor.Agents.Scraper/Extensions/IApplicationBuilderExtensions.cs
src/Promitor.Agents.Scraper/Startup.cs

chore: Log Prometheus sink URL

---

src/Promitor.Agents.Scraper/Startup.cs

fix: Revert accidential OpenAPI docs change

---

charts/promitor-agent-resource-discovery/README.md
charts/promitor-agent-resource-discovery/templates/configmap.yaml
charts/promitor-agent-resource-discovery/values.yaml
docs/configuration/v2.x/runtime/resource-discovery.md
src/Promitor.Agents.ResourceDiscovery/Configuration/AgentRuntimeConfiguration.cs
src/Promitor.Agents.ResourceDiscovery/Configuration/CacheConfiguration.cs
src/Promitor.Agents.ResourceDiscovery/Controllers/DiscoveryController.cs
src/Promitor.Agents.ResourceDiscovery/Docs/Open-Api.xml
src/Promitor.Agents.ResourceDiscovery/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Agents.ResourceDiscovery/Repositories/CachedResourceRepository.cs
src/Promitor.Agents.ResourceDiscovery/Repositories/Interfaces/IResourceRepository.cs
src/Promitor.Agents.ResourceDiscovery/Repositories/ResourceRepository.cs
src/Promitor.Agents.ResourceDiscovery/Startup.cs
src/Promitor.Agents.Scraper/Health/ResourceDiscoveryHealthCheck.cs

feat: Provide caching on resource discovery agent

---

src/Promitor.Agents.Core/Controllers/OperationController.cs
src/Promitor.Agents.ResourceDiscovery/Controllers/HealthController.cs
src/Promitor.Agents.ResourceDiscovery/Docs/Open-Api.xml
src/Promitor.Agents.Scraper/Controllers/v1/HealthController.cs
src/Promitor.Agents.Scraper/Docs/Open-Api.xml

Provide capability to report basic health, without dependencies, to avoid hitting service limitations for noisy health consumers.

feat: Provide capability to report basic health, without dependencies

---

changelog/content/deprecated/helm-chart-registry.md
docs/deployment/migrate-to-new-helm-registry.md
docs/index.md

Fixes https://github.com/tomkerkhove/promitor/issues/1437

docs: Provide deprecation notice & migration guide for Helm registry deprecation

---

build/azure-devops/agents-resource-discovery-release-official.yml
build/azure-devops/agents-scraper-release-official.yml
changelog/content/deprecated/docker-hub-containers.md
docs/deployment/resource-discovery/index.md
docs/deployment/scraper/index.md
docs/index.md
src/docker-compose.yml

Moving container images from Docker Hub to GitHub Container Registry

docs: Moving container images from Docker Hub to GitHub Container Registry

---

build/azure-devops/agents-resource-discovery-release-official.yml
build/azure-devops/agents-scraper-release-official.yml

- Provide option to create GitHub release for Scraper agent
- Fix bad indention

feat: Provide option to create GitHub release for Scraper agent

---

docs/concepts/how-it-works.md

docs: Fix broken link

---

src/Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj
src/Promitor.Core.Scraping/Promitor.Core.Scraping.csproj
src/Promitor.Integrations.Sinks.Prometheus/PrometheusScrapingEndpointMetricSink.cs
src/Promitor.Integrations.Sinks.Prometheus/Promitor.Integrations.Sinks.Prometheus.csproj
src/Promitor.Integrations.Sinks.Prometheus/RuntimeMetricsCollector.cs
src/Promitor.Tests.Unit/Metrics/Sinks/PrometheusScrapingEndpointMetricSinkTests.cs

Bump Prometheus.Client and resolve breaking change

chore(deps): Update Prometheus.Client to v4.3.0

---

.github/ISSUE_TEMPLATE/feature_request.yml

Tweak issue forms for bugs & feature requests

fix: Tweak issue forms for bugs & feature requests

---

SECURITY.md

docs: Update security policy to only cover v1.6.x and above

---

changelog/content/experimental/unreleased.md
config/promitor/resource-discovery/resource-discovery-declaration.yaml
src/Promitor.Agents.ResourceDiscovery/Graph/Query/GraphQueryBuilder.cs
src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs

fix: Provide case invarient lookups for resource group filtering

---

docs/deployment/resource-discovery/index.md

Fixes dead links to the discovery agent values file and resource discovery doc

docs: fix dead links

---

.github/ISSUE_TEMPLATE/1_feature_request_legacy.yml
.github/ISSUE_TEMPLATE/2_bug_report_legacy.yml
.github/ISSUE_TEMPLATE/3_security_issue_legacy.yml

Use unique names for issue templates

fix: Use unique names for issue templates

---

config/promitor/scraper/metrics.yaml

chore: Update config for Azure Front Door

---

changelog/content/released/v0.2.0-resource-discovery.md
changelog/content/released/v2.1.0-scraper.md
changelog/content/released/v2.1.1-scraper.md

fix: Changelog ordering of releases

---

changelog/content/experimental/unreleased.md
docs/configuration/v2.x/azure-authentication.md
docs/configuration/v2.x/runtime/resource-discovery.md
docs/configuration/v2.x/runtime/scraper.md
docs/index.md

docs: Provide documentation & changelog for Managed Identity support

---

changelog/content/experimental/unreleased.md
changelog/content/released/v0.4.0-resource-discovery.md
changelog/content/released/v2.3.0-scraper.md

docs: Changelog for Scraper v2.3.0 & Resource Discovery v0.4.0

---

docs/configuration/v2.x/azure-authentication.md

docs: Managed identity required cluster on Microsoft Azure

---

changelog/content/experimental/unreleased.md
changelog/content/released/v0.4.1-resource-discovery.md
changelog/content/released/v2.4.0-scraper.md

Update changelog with Scraper - v2.4.0 & Resource Discovery - v0.4.1.

docs: Update changelog with Scraper - v2.4.0 & Resource Discovery - v0.4.1

---

src/Promitor.Tests.Integration/Clients/ScraperClient.cs
src/Promitor.Tests.Integration/Promitor.Tests.Integration.csproj
src/Promitor.Tests.Integration/Services/Scraper/MetricSinks/PrometheusScrapeMetricSinkTests.cs

Provide integration test to verify metrics are reported in Prometheus.
Relates to #1698

test: Provide integration test to verify metrics are reported in Prometheus

---

docs/Gemfile.lock

docs: Fix nokogiri issues

---

build/azure-devops/variables/tests.yml
src/Promitor.Agents.Core/Extensions/IApplicationBuilderExtensions.cs
src/Promitor.Agents.Core/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Agents.Core/Promitor.Agents.Core.csproj
src/Promitor.Agents.ResourceDiscovery/Startup.cs
src/Promitor.Agents.Scraper/Extensions/IApplicationBuilderExtensions.cs
src/Promitor.Agents.Scraper/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj
src/Promitor.Tests.Integration/Clients/AgentClient.cs
src/Promitor.Tests.Integration/Clients/ScraperClient.cs
src/Promitor.Tests.Integration/Promitor.Tests.Integration.csproj
src/Promitor.Tests.Integration/Services/ResourceDiscovery/PrometheusSystemMetricsTests.cs
src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryIntegrationTest.cs
src/Promitor.Tests.Integration/Services/Scraper/MetricSinks/PrometheusSystemMetricsTests.cs
src/Promitor.Tests.Integration/appsettings.json

- Expose Prometheus metrics endpoint for resource discovery
- Provide Prometheus metric for HTTP performance in resource discovery
- Provide system metric for .NET for both agents
Relates to #1717
Relates to #341

feat: Provide Prometeus metrics for Resource Discovery runtime

---

changelog/content/experimental/unreleased.md
changelog/content/released/v0.5.0-resource-discovery.md
changelog/content/released/v2.5.0-scraper.md

Publish new release in changelog

docs: Publish new release in changelog

---

README.md
config/promitor/scraper/metrics.yaml
development-guide.md
tests/README.md
tests/performance/steady-load-resource-discovery-health.yml
tests/performance/steady-load-scraper-scrape.yml

test: Provide guidance on how to run basic performance benchmarks

---

README.md
adding-a-new-scraper.md

docs: Provide documentation on writing integration tests & testing infrastructure

---

docs/configuration/v2.x/metrics/container-registry.md

docs: Added Azure Monitor docs link on ACR page

---

changelog/content/experimental/unreleased.md
changelog/content/released/v0.7.0-resource-discovery.md
changelog/content/released/v2.6.0-scraper.md

Update changelog with new versions

docs: Update changelog with new versions

---

README.md
hackaton.md

Introducing the Promitor hackaton - Contribute & win 🎁

docs: Introducing the Promitor hackaton 🎁

---

.github/workflows/auto-add-issues-to-project.yml

Automatically add new issues to our roadmap on

feat: Automatically add new issues to our roadmap

---

docs-vnext/docs/index.md
docs-vnext/mkdocs.yml

Improve new docs with footer additions, theme toggle and more. Also, started sponsoring the maintainer of the theme.
Relates to #540

docs: Improve new docs with footer additions, theme toggle and more

---

changelog/content/experimental/unreleased.md
changelog/content/released/v0.7.1-resource-discovery.md
changelog/content/released/v2.6.1-scraper.md

Provide changelog for new scraper versions

docs: Provide changelog for new scraper versions

---

src/Promitor.Agents.Scraper/Validation/Steps/Sinks/AtlassianStatuspageMetricSinkValidationStep.cs
src/Promitor.Core.Scraping/Configuration/Providers/MetricsDeclarationProvider.cs

Align code quality with new R# checks

fix: Align code quality with new R# checks

---

changelog/content/experimental/unreleased.md

docs: Improve changelog

---

changelog/content/experimental/unreleased.md
src/Promitor.Agents.Scraper/AzureMonitorClientFactory.cs
src/Promitor.Agents.Scraper/Docs/Open-Api.xml
src/Promitor.Agents.Scraper/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Agents.Scraper/Scheduling/ResourcesScrapingJob.cs
src/Promitor.Agents.Scraper/Scheduling/SchedulingExtensions.cs
src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs
src/Promitor.Integrations.AzureMonitor/Configuration/AzureMonitorConfiguration.cs
src/Promitor.Integrations.AzureMonitor/Configuration/AzureMonitorHistoryConfiguration.cs
src/Promitor.Integrations.AzureMonitor/Configuration/AzureMonitorIntegrationConfiguration.cs
src/Promitor.Tests.Unit/Configuration/RuntimeConfigurationUnitTest.cs
src/Promitor.Tests.Unit/Generators/Config/RuntimeConfigurationGenerator.cs

Reduce metric payloads by only taking last 12 hours.
Fixes #2023

feat: Reduce metric payloads by only taking last 12 hours

---

src/Promitor.Agents.ResourceDiscovery/Dockerfile.linux
src/Promitor.Agents.ResourceDiscovery/Dockerfile.windows
src/Promitor.Agents.Scraper/Dockerfile.linux
src/Promitor.Agents.Scraper/Dockerfile.windows

fix: Avoid globalization issues

---

build/azure-devops/agents-ci-discovery.yml
build/azure-devops/agents-ci-scraper.yml
build/azure-devops/templates/prometheus/show-prometheus-metrics.yml

Show Prometheus output at end of CI run to help failing test analysis.

test: Show Prometheus output at end of CI run

---

changelog/content/experimental/unreleased.md
changelog/content/released/v2.8.0-scraper.md

Provide Scraper v2.8.0 release changelog

docs: Provide Scraper v2.8.0 release changelog

---

src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs

Update expectations to align with Azure infrastructure

test: Update expectations to align with Azure infrastructure

---

config/promitor/scraper/metrics.yaml
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceDiscoveryFactory.cs

Ensure Azure Container Apps discovery is correctly set up
Fixes #2226

fix: Ensure Azure Container Apps discovery is correctly set up

---

changelog/content/experimental/unreleased.md

docs(changelog): Fixed a bug for container instance discovery

---

src/Promitor.Core/Metrics/Sinks/MetricSinkWriter.cs
src/Promitor.Integrations.AzureMonitor/ArmUserAgent.cs
src/Promitor.Integrations.AzureMonitor/RequestHandlers/AzureResourceManagerThrottlingRequestHandler.cs
src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs
src/Promitor.Tests.Unit/Azure/ArmUserAgentTests.cs
src/Promitor.Tests.Unit/Metrics/MetricSinkWriterTests.cs

feat: Improve user-agent for ARM (#2234

---

build/azure-devops/variables/build.yml
changelog/content/experimental/unreleased.md
src/Promitor.Agents.Core/Promitor.Agents.Core.csproj
src/Promitor.Agents.ResourceDiscovery/Dockerfile.linux
src/Promitor.Agents.ResourceDiscovery/Dockerfile.windows
src/Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj
src/Promitor.Agents.Scraper/Dockerfile.linux
src/Promitor.Agents.Scraper/Dockerfile.windows
src/Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj
src/Promitor.Agents.Scraper/Validation/Steps/ConfigurationPathValidationStep.cs
src/Promitor.Agents.Scraper/Validation/Steps/Sinks/AtlassianStatuspageMetricSinkValidationStep.cs
src/Promitor.Agents.Scraper/Validation/Steps/Sinks/OpenTelemetryCollectorMetricSinkValidationStep.cs
src/Promitor.Agents.Scraper/Validation/Steps/Sinks/PrometheusScrapingEndpointMetricSinkValidationStep.cs
src/Promitor.Agents.Scraper/Validation/Steps/Sinks/StatsDMetricSinkValidationStep.cs
src/Promitor.Core.Contracts/Promitor.Core.Contracts.csproj
src/Promitor.Core.Scraping/Promitor.Core.Scraping.csproj
src/Promitor.Core.Telemetry/Promitor.Core.Telemetry.csproj
src/Promitor.Core/Promitor.Core.csproj
src/Promitor.Integrations.Azure/Promitor.Integrations.Azure.csproj
src/Promitor.Integrations.AzureMonitor/Promitor.Integrations.AzureMonitor.csproj
src/Promitor.Integrations.AzureStorage/Promitor.Integrations.AzureStorage.csproj
src/Promitor.Integrations.LogAnalytics/Promitor.Integrations.LogAnalytics.csproj
src/Promitor.Integrations.Sinks.Atlassian.Statuspage/Promitor.Integrations.Sinks.Atlassian.Statuspage.csproj
src/Promitor.Integrations.Sinks.OpenTelemetry/Promitor.Integrations.Sinks.OpenTelemetry.csproj
src/Promitor.Integrations.Sinks.Prometheus/Promitor.Integrations.Sinks.Prometheus.csproj
src/Promitor.Integrations.Sinks.Statsd/Promitor.Integrations.Sinks.Statsd.csproj
src/Promitor.Tests.Integration/Clients/AgentClient.cs
src/Promitor.Tests.Integration/Promitor.Tests.Integration.csproj
src/Promitor.Tests.Unit/Promitor.Tests.Unit.csproj

chore(deps): Migrate to .NET 7

---

.github/workflows/auto-add-issues-to-project.yml

Use GA API for GitHub Projects

fix(automation): Use GA API for GitHub Projects

---

.github/workflows/preview-images.yml
.github/workflows/templates-build-push-image.yml

Automatically publish preview image from master branch

feat: Automatically publish preview image from master branch (#2246

---

README.md

Provide overview of all available images available to end-users/contributors.
Relates to #1805

docs: Provide overview of all available images

---

.github/workflows/templates-build-push-image.yml
README.md

Provide semver tag for master image as well (without git commit) for ease of use

feat: Provide semver tag for master image as well (without git commit)

---

changelog/content/experimental/unreleased.md

Relates to https://github.com/tomkerkhove/promitor/issues/2229
Relates to https://github.com/tomkerkhove/promitor/issues/2230

docs(changelog): List fixed vulnerabilities

---

changelog/content/experimental/unreleased.md

docs(changelog): Order changes by change type (#2253

---

changelog/content/experimental/unreleased.md
changelog/content/released/v0.9.0-resource-discovery.md
changelog/content/released/v2.9.0-scraper.md

Publish changelog for new agent versions

docs: Publish changelog for new agent versions

---

changelog/content/released/v0.9.0-resource-discovery.md
changelog/content/released/v2.9.0-scraper.md

docs: Update release timestamp in changelog

---

build/azure-devops/agents-ci-discovery.yml
build/azure-devops/agents-ci-scraper.yml
config/promitor/resource-discovery/resource-discovery-declaration.yaml
config/promitor/resource-discovery/runtime.yaml
config/promitor/scraper/metrics.yaml
config/promitor/scraper/runtime.yaml

Use new Azure subscription.
Relates to https://github.com/tomkerkhove/promitor/issues/2274
Relates to https://github.com/promitor/azure-infrastructure/issues/49

test: Use new Azure subscription

---

.github/workflows/ci-code.yml
.github/workflows/publish-ci-test-report.yml

https://github.com/dorny/test-reporter#recommended-setup-for-public-repositories to fix external PR failure for publishing test results (see https://github.com/dorny/test-reporter/issues/168#issuecomment-1537331650)

test: Follow recommended setup for public repositories by Test Reporter

---

.github/workflows/publish-ci-test-report.yml

Improve reporting test results

test: Improve reporting test results

---

.github/workflows/pr-post-comment.yml

chore: Provide PR bot

---

config/promitor/scraper/metrics.yaml

ci: fix resources after migrating to a new Azure subscription

---

build/azure-devops/variables/build.yml
changelog/content/experimental/unreleased.md
src/Promitor.Agents.Core/Promitor.Agents.Core.csproj
src/Promitor.Agents.ResourceDiscovery/Dockerfile.linux
src/Promitor.Agents.ResourceDiscovery/Dockerfile.windows
src/Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj
src/Promitor.Agents.Scraper/Dockerfile.linux
src/Promitor.Agents.Scraper/Dockerfile.windows
src/Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj
src/Promitor.Core.Contracts/Promitor.Core.Contracts.csproj
src/Promitor.Core.Scraping/Promitor.Core.Scraping.csproj
src/Promitor.Core/Promitor.Core.csproj
src/Promitor.Integrations.Azure/Promitor.Integrations.Azure.csproj
src/Promitor.Integrations.AzureMonitor/Promitor.Integrations.AzureMonitor.csproj
src/Promitor.Integrations.AzureStorage/Promitor.Integrations.AzureStorage.csproj
src/Promitor.Integrations.LogAnalytics/Promitor.Integrations.LogAnalytics.csproj
src/Promitor.Integrations.Sinks.Atlassian.Statuspage/Promitor.Integrations.Sinks.Atlassian.Statuspage.csproj
src/Promitor.Integrations.Sinks.OpenTelemetry/Promitor.Integrations.Sinks.OpenTelemetry.csproj
src/Promitor.Integrations.Sinks.Prometheus/Promitor.Integrations.Sinks.Prometheus.csproj
src/Promitor.Integrations.Sinks.Statsd/Promitor.Integrations.Sinks.Statsd.csproj
src/Promitor.Tests.Integration/Promitor.Tests.Integration.csproj
src/Promitor.Tests.Unit/Promitor.Tests.Unit.csproj

chore(deps): update .net runtime to 7.0.5 and .net sdk to 7.0.302

---

changelog/content/experimental/unreleased.md
src/Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj
src/Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj

chore(deps): bump System.Security.Cryptography.Pkcs to fix CVE-2023-29331

---

build/azure-devops/agents-ci-discovery.yml
build/azure-devops/agents-ci-scraper.yml
build/azure-devops/agents-resource-discovery-release-official.yml
build/azure-devops/agents-scraper-release-official.yml
build/azure-devops/templates/tests/run-integration-tests.yml

Introduce test run titles to seperate Linux/Windows results

test: Introduce test run titles to seperate Linux/Windows results

---

changelog/content/experimental/unreleased.md
changelog/content/released/v0.10.0-resource-discovery.md
changelog/content/released/v2.10.0-scraper.md

Publish Scraper v2.10.0 & Discovery v0.10 release notes

docs: Publish Scraper v2.10.0 & Discovery v0.10 release notes

---

changelog/content/experimental/unreleased.md

Additional note to the documentation for the hotfix of multi dimension support on StatsD sink

docs: Publish hotfix of multi dimension support on StatsD sink note

---

changelog/content/experimental/unreleased.md
changelog/content/released/v0.11.1-resource-discovery.md
changelog/content/released/v2.11.1-scraper.md

docs: Changelog v2.11.1 & v0.11.1

---

src/Promitor.Agents.Core/Promitor.Agents.Core.csproj
src/Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj
src/Promitor.Tests.Integration/Promitor.Tests.Integration.csproj

Reverts tomkerkhove/promitor#2437

revert: "chore(deps): update arcus.observability monorepo to v3"

---

src/Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj

Reverts tomkerkhove/promitor#2461

revert: "chore(deps): update dependency microsoft.visualstudio.azure.containers.tools.targets to v1.20.1"

---

src/Promitor.Tests.Integration/Promitor.Tests.Integration.csproj
src/Promitor.Tests.Unit/Promitor.Tests.Unit.csproj

Reverts tomkerkhove/promitor#2468

revert "chore(deps): update xunit-dotnet monorepo"

---

src/Promitor.Tests.Integration/Promitor.Tests.Integration.csproj
src/Promitor.Tests.Unit/Promitor.Tests.Unit.csproj

Reverts tomkerkhove/promitor#2451

revert "chore(deps): update dependency bogus to v35.5.0"

---

src/Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj

Reverts tomkerkhove/promitor#2464

revert: "chore(deps): update dependency microsoft.azure.kusto.language to v11.5.2"

---

src/Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj
src/Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj

Reverts tomkerkhove/promitor#2456

revert "chore(deps): update dependency system.drawing.common to v8.0.4"

---

src/Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj
src/Promitor.Tests.Integration/Promitor.Tests.Integration.csproj

Reverts tomkerkhove/promitor#2452

revert "chore(deps): update dependency polly to v8.3.1"

---

src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs

Align expectations with test infra

fix(tests): Align expectations with test infra

---

src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs

Align test expectations with reality

test: Align test expectations with reality

---

.github/workflows/templates-build-push-image.yml
changelog/content/experimental/unreleased.md

Just tidying things up here for the upcoming release. Feel free to rephrase as you see fit and merge it. Thanks!

chore: add changelog for batch scraping

---

changelog/content/experimental/unreleased.md
changelog/content/released/v0.12.0-resource-discovery.md
changelog/content/released/v2.12.0-scraper.md

Changelog for Scraper v2.12.0 & Resource Discovery v0.12.0

feat: Changelog for Scraper v2.12.0 & Resource Discovery v0.12.0

---

.github/workflows/ci-code.yml
.github/workflows/codeql-analysis.yml

Use .NET 8 in automation to fix automation

fix: Use .NET 8 in automation

---

build/azure-devops/variables/build.yml
src/Promitor.Agents.Core/Promitor.Agents.Core.csproj
src/Promitor.Agents.ResourceDiscovery/Dockerfile.linux
src/Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj
src/Promitor.Agents.Scraper/Dockerfile.linux
src/Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj
src/Promitor.Core.Contracts/Promitor.Core.Contracts.csproj
src/Promitor.Core.Scraping/Promitor.Core.Scraping.csproj
src/Promitor.Core.Telemetry/Promitor.Core.Telemetry.csproj
src/Promitor.Core/Promitor.Core.csproj
src/Promitor.Integrations.Azure/Promitor.Integrations.Azure.csproj
src/Promitor.Integrations.AzureMonitor/Promitor.Integrations.AzureMonitor.csproj
src/Promitor.Integrations.AzureStorage/Promitor.Integrations.AzureStorage.csproj
src/Promitor.Integrations.LogAnalytics/Promitor.Integrations.LogAnalytics.csproj
src/Promitor.Integrations.Sinks.Atlassian.Statuspage/Promitor.Integrations.Sinks.Atlassian.Statuspage.csproj
src/Promitor.Integrations.Sinks.Core/Promitor.Integrations.Sinks.Core.csproj
src/Promitor.Integrations.Sinks.OpenTelemetry/Promitor.Integrations.Sinks.OpenTelemetry.csproj
src/Promitor.Integrations.Sinks.Prometheus/Promitor.Integrations.Sinks.Prometheus.csproj
src/Promitor.Integrations.Sinks.Statsd/Promitor.Integrations.Sinks.Statsd.csproj
src/Promitor.Tests.Integration/Promitor.Tests.Integration.csproj
src/Promitor.Tests.Unit/Promitor.Tests.Unit.csproj

This PR updates the .NET runtime and security-critical packages to their latest versions to address potential vulnerabilities.
- Updated `RuntimeFrameworkVersion` from **8.0.18** to **8.0.20** across all 18 projects
- Updated Docker base images to use **8.0.20-cbl-mariner2.0-distroless**
- **System.Drawing.Common**: `9.0.2` → `9.0.9`
- **System.Security.Cryptography.Pkcs**: `8.0.1` → `9.0.9`
- **System.Security.Cryptography.Xml**: `8.0.2` → `9.0.9`
- Removed vulnerable **System.Text.RegularExpressions v4.3.1** (affected by CVE-2019-0820)
✅ **Build Status**: Full solution builds successfully with zero warnings
✅ **Tests**: All 1,513 unit tests pass
✅ **Security Scan**: Zero vulnerable packages detected
✅ **Functionality**: All core functionality verified working
- 18 `.csproj` project …

chore: update .NET runtime to 8.0.20 and security packages to latest versions
