docs/index.md

Use spaces instead of tabs in cmd snippet

---

.github/CONTRIBUTING.md
README.md

Introduce Contribution guide that will be shown when creating issues & PRs.
More information in GitHub [docs](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)

Introduce Contribution guide

---

.travis.yml

- Remove Solution and do everything with dotnet to avoid restoring & building twice
- Only scan host

Travis CI - Reduce build time

---

src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs
src/Promitor.Integrations.AzureMonitor/Exceptions/MetricInformationNotFoundException.cs
src/Promitor.Integrations.AzureMonitor/Exceptions/MetricNotFoundException.cs
src/Promitor.Integrations.AzureMonitor/Promitor.Integrations.AzureMonitor.csproj
src/Promitor.Scraper.Host/Configuration/Serialization/AzureMetadataDeserializer.cs
src/Promitor.Scraper.Host/Configuration/Serialization/AzureMetricConfigurationDeserializer.cs
src/Promitor.Scraper.Host/Configuration/Serialization/ConfigurationSerializer.cs
src/Promitor.Scraper.Host/Configuration/Serialization/Deserializer.cs
src/Promitor.Scraper.Host/Configuration/Serialization/MetricsDeserializer.cs
src/Promitor.Scraper.Host/Dockerfile
src/Promitor.Scraper.Host/Docs/Open-Api.xml
src/Promitor.Scraper.Host/Promitor.Scraper.Host.csproj
src/Promitor.Scraper.Host/Scraping/Scraper.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/MetricsValidator.cs

This PR closes the security vulnerability in Microsoft.AspNetCore.App v2.1.3 and closes #167

Update Guard.NET to v1.2 & Microsoft.AspNetCore.App to v2.1.4

---

src/Promitor.Scraper.Host/Configuration/Serialization/AzureMetricConfigurationDeserializer.cs

When a yaml configuration is presented without aggregation type for `azureMetricConfiguration`, the deserializer would fail. This changes the behavior to fallback to the default value (None).
Sample failing yaml:
```yml
azureMetadata:
resourceGroupName: Rhiannon
subscriptionId: 75226421
tenantId: 01079505
metrics:
- namespace: Ernser
queueName: Polly
resourceType: ServiceBusQueue
metricName: Demetrius
description: Eligendi minima est dolorum explicabo rem.
name: Gaston
```
Fixes #159, which would occur when Bogus generates data with an aggregation set to `None`.

Be more resilient when deserializing aggregation enum

---

src/Promitor.Integrations.AzureMonitor/Promitor.Integrations.AzureMonitor.csproj
src/Promitor.Scraper.Host/Dockerfile
src/Promitor.Scraper.Host/Promitor.Scraper.Host.csproj

Upgrade to .NET 2.2.1 to mitigate CVE-2019-0548 & CVE-2019-0564
Closes #267

Upgrade to .NET 2.2.1 to mitigate CVE-2019-0548 & CVE-2019-0564

---

samples/promitor-sample.yaml
src/Promitor.Core.Scraping/ResourceTypes/StorageQueueScraper.cs
src/Promitor.Integrations.AzureStorage/AzureStorageClient.cs
src/Promitor.Integrations.AzureStorage/AzureStorageQueueClient.cs
src/Promitor.Integrations.AzureStorage/Exceptions/QueueNotFoundException.cs
src/Promitor.Integrations.AzureStorage/Promitor.Integrations.AzureStorage.csproj
src/Promitor.Scraper.Host/Scheduling/MetricScrapingJob.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/StorageQueueMetricValidator.cs

Verify that storage queue to monitor exists

Verify that storage queue to monitor exists

---

docs/configuration/metrics/generic-azure-resource.md
docs/configuration/metrics/index.md
docs/configuration/metrics/service-bus-queue.md
docs/configuration/metrics/storage-queue.md
samples/promitor-sample.yaml
src/Promitor.Core.Scraping/Constants.cs
src/Promitor.Core.Scraping/ResourceTypes/InvalidMetricNameException.cs
src/Promitor.Core.Scraping/ResourceTypes/StorageQueueScraper.cs
src/Promitor.Integrations.AzureStorage/AzureStorageConstants.cs
src/Promitor.Integrations.AzureStorage/AzureStorageQueueClient.cs
src/Promitor.Scraper.Host/Promitor.Scraper.Host.csproj
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/StorageQueueMetricValidator.cs
src/Promitor.Scraper.Tests.Unit/Builders/MetricsDeclarationBuilder.cs
src/Promitor.Scraper.Tests.Unit/Validation/Metrics/ResourceTypes/AzureStorageQueueMetricsDeclarationValidationStepTests.cs

Improve metric determination for storage queues and streamline metric docs.
Relates to #418

Improve metric determination for storage queues and streamline metric docs

---

CODEOWNERS

Every PR it assign people based on area:
- Docs - @brusmx
- Deploy & Kube chart - @brusmx @jsturtevant
- Code - @brandonh-msft @jsturtevant
This should be fine according to : https://help.github.com/en/articles/about-code-owners

Extend code owners with people from hackaton

---

.azure-devops/agents-scraper-release-official.yaml

Provide build YAML for official release.
Relates to #433 & #393

Provide build YAML for official release

---

adding-a-new-scraper.md
src/Promitor.Scraper.Host/Docs/Open-Api.xml
src/Promitor.Scraper.Host/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/Interfaces/IMetricValidator.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/MetricValidator.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/MetricsValidator.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/GenericAzureMetricValidator.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/ServiceBusQueueMetricValidator.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/StorageQueueMetricValidator.cs
src/Promitor.Scraper.Host/Validation/Steps/MetricsDeclarationValidationStep.cs

Fixes #445
Utilizing the same approach as with deserialization, Validators can now be added by modifying one `switch` statement of a Factory and adding only **new** files to the codebase.
🎉

New YAML Validation code structure

---

docs/configuration/metrics/index.md
docs/configuration/metrics/virtual-machine.md
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/VirtualMachineMetricDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/ResourceType.cs
src/Promitor.Core.Scraping/Configuration/Serialization/Deserializers/VirtualMachineMetricDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricDeserializerFactory.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/VirtualMachineScraper.cs
src/Promitor.Scraper.Host/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/MetricsValidator.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/VirtualMachineMetricValidator.cs
src/Promitor.Scraper.Tests.Unit/Builders/MetricsDeclarationBuilder.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithVirtualMachineYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Validation/Metrics/ResourceTypes/VirtualMachineMetricsDeclarationValidationStepsTests.cs

Provides support for scraping Azure Virtual Machines
Example configuration:
```yaml
name: demo_virtualmachine_percentage_cpu
description: "Average percentage cpu usage of our 'promitor-virtual-machine' virtual machine"
resourceType: VirtualMachine
virtualMachineName: promitor-virtual-machine
metricName: Percentage CPU
aggregation:
type: Average
```
Closes #309

Virtual machine metrics

---

src/Promitor.Scraper.Host/Scheduling/MetricScrapingJob.cs

Track scrape exceptions to STDERR

Track scrape exceptions to STDERR

---

.gitignore
src/Promitor.Core.Scraping/Configuration/Model/MetricDefaults.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/MetricDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Scraping.cs
src/Promitor.Core.Scraping/Configuration/Serialization/Core/MetricDefaultsDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/Core/MetricDeserializer.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithAzureStorageQueueYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithContainerInstanceYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithContainerRegistryYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithServiceBusQueueYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithVirtualMachineYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/YamlSerializationTests.cs

Partial fix for #258, #259
This adds the YAML configuration support for `metricDefaults.scraping.interval` and `<metric>.scraping.interval`. 
As of this PR, however, `metricDefault` does **not** fill out the metric scraping interval if it is not supplied; this work must be done in the scraper and only makes sense after we have fully rid ourselves of the `CronSchedule` Environment parameter. This will be done in a future PR.

Adding scraping interval to metricDefaults and metrics

---

docs/index.md

Fix license on docs page to mention Tom instead of Codit.
Fixes #480

Fix license on docs page

---

charts/promitor-scraper/values.yaml
docs/configuration/index.md
docs/deployment/index.md
src/Promitor.Core.Scraping/ScrapeEndpoint.cs

Change default Prometheus endpoint to /metrics

---

src/Promitor.Integrations.AzureStorage/AzureStorageQueueClient.cs

Support no messages available with TimeSpentInQueue & Storage scraper by tracking 0 seconds if no messages are available.
Fixes #495
When one or more messages are queued:
```
demo_azurestoragequeue_queue_timespentinqueue 15.212368 1554629347212
```
When no message is in queue:
```
demo_azurestoragequeue_queue_timespentinqueue 0 1554629307416
```

Support no messages available with TimeSpentInQueue & Storage scraper

---

docs/index.md

Remove known limitations on docs given we now respect scraping based on schedule which was reported in #60.

Remove known limitations on docs

---

src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/StorageQueueMetricDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/Secret.cs
src/Promitor.Core.Scraping/Configuration/Serialization/Core/SecretDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/Deserializers/StorageQueueMetricDeserializer.cs
src/Promitor.Core.Scraping/ResourceTypes/StorageQueueScraper.cs
src/Promitor.Scraper.Host/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/StorageQueueMetricValidator.cs
src/Promitor.Scraper.Host/Validation/Steps/MetricsDeclarationValidationStep.cs
src/Promitor.Scraper.Tests.Unit/Builders/MetricsDeclarationBuilder.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithAzureStorageQueueYamlSerializationTests.cs
src/docker-compose.override.yml
src/metric-config.yaml

- Provide capability to configure SAS tokens via raw value or environment variable
- Don't log raw configuration to leak configured raw SAS token
Relates to #530 & #514
```yaml
metrics:
- name: demo_azurestoragequeue_queue_size
description: "Approximate amount of messages in 'orders' queue (determined with StorageQueue provider)"
resourceType: StorageQueue
accountName: promitor
queueName: orders
sasToken:
rawValue: "?sv=<redacted>"
metricName: MessageCount
aggregation:
type: Total
- name: demo_azurestoragequeue_queue_timespentinqueue
description: "Approximate amount of time that the oldest message has been in 'orders' queue (determined with StorageQueue provider)"
resourceType: StorageQueue
accountName: promitor
queueName: orders
sasToken:
environmentVariable: …
```

 Provide capability to configure SAS tokens via raw value or environment variable & don't log raw configuration

---

docs/index.md
docs/operations/index.md
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/Scraper.cs
src/Promitor.Core.Telemetry.Metrics/Interfaces/IRuntimeMetricsCollector.cs
src/Promitor.Core.Telemetry.Metrics/Promitor.Core.Telemetry.Metrics.csproj
src/Promitor.Core.Telemetry.Metrics/RuntimeMetricNames.cs
src/Promitor.Core.Telemetry.Metrics/RuntimeMetricsCollector.cs
src/Promitor.Core/Infrastructure/FeatureFlag.cs
src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs
src/Promitor.Integrations.AzureMonitor/Promitor.Integrations.AzureMonitor.csproj
src/Promitor.Integrations.AzureMonitor/RequestHandlers/AzureResourceManagerThrottlingRequestHandler.cs
src/Promitor.Scraper.Host/Dockerfile
src/Promitor.Scraper.Host/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Scraper.Host/Scheduling/MetricScrapingJob.cs
src/Promitor.Scraper.Host/Startup.cs
src/Promitor.sln

Insights on ARM Throttling & API consumption via a `promitor_ratelimit_arm_subscription` metric in Prometheus scraping endpoint.
```yaml
promitor_ratelimit_arm{tenant_id="c8819874-9e56-4e3f-b1a8-1c0325138f27",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",app_id="ceb249a3-44ce-4c90-8863-6776336f5b7e"} 11998 1557417726598
```
Relates to #199

Insights on ARM Throttling & API consumption

---

src/Promitor.Core.Scraping/ResourceTypes/ContainerInstanceScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/ContainerRegistryScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/CosmosDbScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/GenericScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/NetworkInterfaceScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/ServiceBusQueueScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/StorageQueueScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/VirtualMachineScraper.cs
src/Promitor.Core.Scraping/ScrapeResult.cs
src/Promitor.Core.Scraping/Scraper.cs

Provide `resource_uri` label for all metrics
Relates to #513
```
demo_azurestoragequeue_queue_size{resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor/providers/Microsoft.Storage/storageAccounts/promitor/queueServices"} 0 1558374841314
demo_azurestoragequeue_queue_timespentinqueue{resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor/providers/Microsoft.Storage/storageAccounts/promitor/queueServices"} 0 1558374902571
demo_generic_namespace_size{resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor/providers/Microsoft.ServiceBus/namespaces/promitor-messaging"} 8195 1558374842091
demo_generic_queue_size{resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/prom …
```

Provide resource_uri label for all metrics

---

src/Promitor.Core.Telemetry/Loggers/Logger.cs

Fixes #571
```shell
██████╗ ██████╗  ██████╗ ███╗   ███╗██╗████████╗ ██████╗ ██████╗
██╔══██╗██╔══██╗██╔═══██╗████╗ ████║██║╚══██╔══╝██╔═══██╗██╔══██╗
██████╔╝██████╔╝██║   ██║██╔████╔██║██║   ██║   ██║   ██║██████╔╝
██╔═══╝ ██╔══██╗██║   ██║██║╚██╔╝██║██║   ██║   ██║   ██║██╔══██╗
██║     ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║   ██║   ╚██████╔╝██║  ██║
╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝
No scraping endpoint was specified, falling back to default '/metrics'...
No scraping configuration path was specified, falling back to default '/config/metrics-declaration.yaml'...
info: Validation[0]
[2019-06-08 08:13:05Z] Starting validation of Promitor setup
info: Validation[0]
[2019-06-08 08:13:05Z] Start Validation step 1/4: Metrics Declaration Path
warn: Validation[0] …
```

Provide timestamps for logging

---

charts/promitor-agent-scraper/templates/service.yaml

Expose Promitor via LoadBalancer service in Kubernetes, depending on Helm configuration
Fixes #572

Expose Promitor via LoadBalancer service in Kubernetes 

---

src/Promitor.Core.Scraping/Scraper.cs

Update `ScrapeAsync` method to raise better exception when Azure monitoring is returning a JSON Payload in its Response.
The json payload looks like this:
``` json
{
"error": {
"code": "xxxx",
"message" : "zzzz"
}
}
```
From the `Microsoft.Azure.Management.Monitor.Fluent` SDK, we have a wrapped exception `ErrorResponseException` used here to get the detailed message

Raising a better exception message from Azure Monitoring http response

---

src/Promitor.Core.Scraping/ResourceTypes/ContainerInstanceScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/ContainerRegistryScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/CosmosDbScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/GenericScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/NetworkInterfaceScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/PostgreSqlScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/RedisCacheScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/ServiceBusQueueScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/StorageQueueScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/VirtualMachineScraper.cs
src/Promitor.Core.Scraping/ScrapeResult.cs
src/Promitor.Core.Scraping/Scraper.cs

Provide labels with resource information such as:
- Subscription id
- Resource group name
- Instance name
- Detailed information such as queue name
Closes #598
```
promitor_demo_azurestoragequeue_queue_size{resource_group="promitor",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor/providers/Microsoft.Storage/storageAccounts/promitor/queueServices",instance_name="promitor",queue_name="orders"} 0 1561569513810
promitor_demo_azurestoragequeue_queue_timespentinqueue{resource_group="promitor",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor/providers/Microsoft.Storage/storageAccounts/promitor/queueServices", …
```

Provide labels with resource information

---

docs/configuration/metrics/index.md
src/Promitor.Core.Scraping/Configuration/Model/Metrics/MetricDefinition.cs
src/Promitor.Core.Scraping/Configuration/Serialization/Core/ConfigurationSerializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/Core/MetricDeserializer.cs
src/Promitor.Core.Scraping/Scraper.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithAzureStorageQueueYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithContainerInstanceYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithContainerRegistryYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithCosmosDbYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithNetworkInterfaceYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithPostgreSqlYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithRedisCacheYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithServiceBusQueueYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithVirtualMachineYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/YamlSerializationTests.cs
src/metric-config.yaml

Fixes #603
```yaml
azureMetadata:
tenantId: <redacted>
subscriptionId: <redacted>
resourceGroupName: <redacted>
metricDefaults:
aggregation:
interval: 00:05:00
scraping:
schedule: "0 * * ? * *"
metrics:
- name: promitor_demo_generic_queue_size
description: "Amount of active messages of the 'orders' queue (determined with Generic provider)"
resourceType: Generic
resourceUri: Microsoft.ServiceBus/namespaces/promitor-messaging
filter: EntityName eq 'orders'
labels:
app: promitor
metricName: ActiveMessages
aggregation:
type: Average
```
```
promitor_demo_generic_queue_size{resource_group="promitor",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor/providers/Microsoft.ServiceB …
```

Provide capability to specify custom labels per metric

---

src/Promitor.Scraper.Host/Dockerfile

Switch to .NET Core Alpine as Docker base image to get rid of all Docker image security vulnerabilities.
Closes #610

Switch to .NET Core Alpine as Docker base image

---

charts/promitor-agent-scraper/README.md
charts/promitor-agent-scraper/templates/deployment.yaml
charts/promitor-agent-scraper/values.yaml

Currently, the helm chart does not have any resources parameter for the deployment. 
- add `resources` parameter in the helm chart
- keep it to empty for the compatibility

helm: add resources options in the deployment

---

.github/CONTRIBUTING.md

Provide better guidance in contribution guide

Provide better guidance in contribution guide

---

src/Promitor.Core.Telemetry/ApplicationInsightsTelemetry.cs

Enforce instrumentation key when Application Insights is enabled, otherwise there is no point in enabling it.
Relates to #431

Enforce instrumentation key when Application Insights is enabled

---

docs/configuration/v1.x/metrics/service-bus-queue.md
docs/configuration/v1.x/metrics/storage-queue.md
docs/configuration/v1.x/runtime.md
docs/index.md
docs/metrics/labels.md

 Provide documentation on metric labelling

---

src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/MetricDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/ContainerInstanceMetricDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/ContainerRegistryMetricDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/CosmosDbMetricDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/GenericAzureMetricDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/NetworkInterfaceMetricDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/PostgreSqlMetricDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/RedisCacheMetricDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/ServiceBusQueueMetricDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/StorageQueueMetricDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/VirtualMachineMetricDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricDeserializerFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/ContainerInstanceScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/NetworkInterfaceScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/VirtualMachineScraper.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithAzureStorageQueueYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithContainerInstanceYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithContainerRegistryYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithCosmosDbYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithNetworkInterfaceYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithPostgreSqlYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithRedisCacheYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithServiceBusQueueYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/MetricsDeclarationWithVirtualMachineYamlSerializationTests.cs
src/Promitor.Scraper.Tests.Unit/Serialization/MetricsDeclaration/YamlSerializationTests.cs

The ability to override the resource group per metric was broken for all resource types other than the Generic resource type.
This commit:
- Fixes the tests for all resource types to test for this by removing the `Ignore()` method calls for the `ResourceGroupName` property and added an extra assert to check for the resource group.
- Alters the deserializers to inherit directly from `MetricDeserializer` rather than `GenericAzureMetricDeserializer`. They weren't actually using any of the functionality from the generic type.
- Fixes a few Scraper implementations to actually use the overridden group name.
Fixes #655

Fix resource group overriding

---

docs/configuration/v1.x/runtime.md
docs/index.md
docs/operations/index.md
src/Promitor.Core/EnvironmentVariables.cs
src/Promitor.Scraper.Host/Program.cs

Provide documentation on overriding runtime config & config APIs.
Fixes #682 
Fixes #673

Provide documentation on overriding runtime config & config APIs

---

adding-a-new-scraper.md
docs/configuration/v1.x/metrics/container-instances.md
docs/configuration/v1.x/metrics/container-registry.md
docs/configuration/v1.x/metrics/cosmos-db.md
docs/configuration/v1.x/metrics/generic-azure-resource.md
docs/configuration/v1.x/metrics/index.md
docs/configuration/v1.x/metrics/network-interface.md
docs/configuration/v1.x/metrics/postgresql.md
docs/configuration/v1.x/metrics/redis-cache.md
docs/configuration/v1.x/metrics/service-bus-queue.md
docs/configuration/v1.x/metrics/storage-queue.md
docs/configuration/v1.x/metrics/virtual-machine.md

- I've updated the documentation and the guide on adding a new scraper to match the changes made to support multiple resources per metric.
- I also tweaked the wording about adding docs in the new scraper guide so it doesn't sound optional. I figured if someone goes to the bother of adding a scraper they can easily add some docs based on the examples that are there.
- Tweaked some of the wording where I spotted a few typos / mistakes while proof-reading.
- I've also tweaked the example metric names used. Some of them didn't make sense now that multiple resources are supported, and I figured it made sense to just do a pass and make them all consistent.
Part of #513.
@tomkerkhove - as part of this I've updated all the resource docs to include two resources in each example to make it clear …

Update documentation for multi-resource changes

---

charts/promitor-agent-scraper/README.md
charts/promitor-agent-scraper/templates/NOTES.txt
charts/promitor-agent-scraper/templates/configmap.yaml
charts/promitor-agent-scraper/values.yaml
docs/deployment/index.md
docs/walkthrough/index.md

General Helm Chart improvements:
- Remove secret from file for Helm deployment guidance
- Remove `runtime` prefix for variables
- Update sample in values.yaml to new metric format
- Align walkthrough with new metric format
Fixes #658

General Helm Chart improvements

---

charts/promitor-agent-scraper/templates/configmap.yaml

Fix broken runtime config name in Helm chart

Fix broken runtime config name in Helm chart

---

charts/promitor-agent-scraper/templates/deployment.yaml

Fixes #669
- As requested in #669 this replaces the deprecated apiVersion extensions/v1beta1 with apps/v1
- The other apiVersions of the helm chart should be fine (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16)
- This breaks the helm chart for clusters with a version <1.9 but this should be fine

Replace deprecated apiVersion extensions/v1beta1 with apps/v1

---

package-lock.json
package.json

I've added [husky](https://github.com/typicode/husky) to run the markdownlint check as a pre-commit hook.
I've also added [lint-staged](https://github.com/okonet/lint-staged), which does a couple of things for us:
- It will only run linters if any files have been changed matching certain patterns. For example, it'll only run the markdownlint check if any `*.md` files have been changed.
- It makes sure that your staged changes are valid so you don't fix a problem then forget to stage it before committing.
Fixes #741
Here's what it looks like if you try to commit a file with a failing markdown check:
```shell
$ git commit -m"Test commit"
husky > pre-commit (node v11.6.0)
Stashing changes... [started]
Stashing changes... [skipped]
→ No partially staged files found...
Running tasks... …
```

Add husky to run markdownlint

---

README.md
development-guide.md
docs/README.md

I've added a new document with information about how to build and test Promitor, along with an overview of the repository layout.
Fixes #484

Add development guide

---

docs/configuration/v0.x/metrics/generic-azure-resource.md
docs/configuration/v0.x/metrics/service-bus-queue.md
docs/configuration/v1.x/metrics/azure-sql-database.md
docs/configuration/v1.x/metrics/container-instances.md
docs/configuration/v1.x/metrics/container-registry.md
docs/configuration/v1.x/metrics/cosmos-db.md
docs/configuration/v1.x/metrics/generic-azure-resource.md
docs/configuration/v1.x/metrics/index.md
docs/configuration/v1.x/metrics/network-interface.md
docs/configuration/v1.x/metrics/postgresql.md
docs/configuration/v1.x/metrics/redis-cache.md
docs/configuration/v1.x/metrics/service-bus-queue.md
docs/configuration/v1.x/metrics/storage-queue.md
docs/configuration/v1.x/metrics/virtual-machine.md
docs/metrics/labels.md
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/AzureSqlDatabaseResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/ResourceType.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureResourceDeserializerFactory.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Mapping/V1MappingProfile.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/ResourceTypes/AzureSqlDatabaseResourceV1.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/AzureSqlDatabaseDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/AzureSqlDatabaseScraper.cs
src/Promitor.Scraper.Host/Docs/Open-Api.xml
src/Promitor.Scraper.Host/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/AzureSqlDatabaseMetricValidator.cs
src/Promitor.Scraper.Tests.Unit/Builders/Metrics/v1/MetricsDeclarationBuilder.cs
src/Promitor.Scraper.Tests.Unit/Serialization/v1/Providers/AzureSqlDatabaseDeserializerTests.cs
src/Promitor.Scraper.Tests.Unit/Validation/Metrics/ResourceTypes/AzureSqlDatabaseMetricsDeclarationValidationStepTests.cs

Fixes #317
- Implements a scraper for Azure SQL Database.
Here's an example of the metric output:
```text
azure_sql_database_dtu_consumption_percent{resource_group="promitor-group",subscription_id="<subscription-id>",resource_uri="subscriptions/<subscription-id>/resourceGroups/promitor-group/providers/Microsoft.Sql/servers/promitor-server/databases/database-1",server="promitor-server",database="database-1"} 70.4375
azure_sql_database_dtu_consumption_percent{resource_group="promitor-group",subscription_id="<subscription-id>",resource_uri="subscriptions/<subscription-id>/resourceGroups/promitor-group/providers/Microsoft.Sql/servers/promitor-server/databases/database-2",server="promitor-server",database="database-2"} 0
```

Add an Azure SQL Database scraper

---

charts/promitor-agent-scraper/templates/NOTES.txt

Fix incorrect notes instructions. Namespace was missing in the port-forward command, and use 0.0.0.0 IP for the curl command (127.0.0.1 doesn't work).

Fix incorrect notes instructions

---

build/azure-devops/scraper-ci.yml
package.json

- Updated the markdownlint command to ignore the changelog folder.
- Re-added the check into the pipeline.
Fixes #775
@tomkerkhove for now I've just configured it to ignore the entire changelog folder because when I just ignored `changelog/themes` there were linting errors in some of the other files, and I wasn't sure if they were generated or not. If you pull down the branch you can easily try it out by changing the `--ignore changelog` to `--ignore changelog/themes` in the package.json file, and then just run `npm run markdownlint` to run the checks.

Ignore changelog folder in markdown linting

---

build/azure-devops/agents-scraper-release-official-helm.yml
build/azure-devops/agents-scraper-release-official.yml

Update GitHub releases to include changelog.promitor.io and list new deprecations.
Relates to #753

Update GitHub releases to include changelog.promitor.io

---

build/azure-devops/agents-scraper-release-official.yml
build/azure-devops/templates/persist-variable.yml
build/azure-devops/templates/read-variable.yml

Based on https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable.
Fixes #709

Ensure that Image.MajorMinorVersion is set in official releases

---

changelog/content/experimental/unreleased.md
docs/configuration/v1.x/metrics/index.md
docs/configuration/v1.x/metrics/virtual-machine-scale-set.md
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/SqlManagedInstanceResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/VirtualMachineScaleSetsResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/ResourceType.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureResourceDeserializerFactory.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Mapping/V1MappingProfile.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/ResourceTypes/VirtualMachineScaleSetResourceV1.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/VirtualMachineScaleSetDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/SqlManagedInstanceScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/VirtualMachineScaleSetScraper.cs
src/Promitor.Scraper.Host/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Scraper.Host/Validation/MetricDefinitions/ResourceTypes/VirtualMachineScaleSetMetricValidator.cs
src/Promitor.Scraper.Tests.Unit/Builders/Metrics/v1/MetricsDeclarationBuilder.cs
src/Promitor.Scraper.Tests.Unit/Serialization/v1/Providers/VirtualMachineScaleSetDeserializerTests.cs
src/Promitor.Scraper.Tests.Unit/Validation/Metrics/ResourceTypes/VirtualMachineScaleSetMetricsDeclarationValidationStepsTests.cs

Provide Azure Virtual Machine Scale Set (VMSS) Scraper

---

changelog/content/experimental/unreleased.md
src/Promitor.Core.Scraping/Prometheus/PrometheusMetricWriter.cs

Metric labels for dimensions should always be lower-cased for consistency reasons.

Metric labels for dimensions should always be lower-cased

---

build/azure-devops/scraper-ci.yml

Introduce new job for Helm linting to cover Helm 2.x & Helm 3.x

Introduce new job for Helm linting to cover Helm 2.x & Helm 3.x

---

build/azure-devops/scraper-ci.yml
docs/configuration/v1.x/metrics/sql-server.md

markdownlint was complaining because there was a blockquote defined without an angle bracket on each line. This triggered <https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md027---multiple-spaces-after-blockquote-symbol>.
I think what's happened is that the docs folder wasn't configured to trigger an Azure Pipelines build, so the check was never run on the PR. I've updated the pipelines file to trigger a build on changes to the docs folder now.
@tomkerkhove do you think it makes sense to have a separate pipeline for the docs folder so it doesn't need to run a full build of the code if you're just making a documentation change? I went with the easy option of just adding the docs folder for now, but I figured it was worth asking.

Fix MD027 violation on sql-server.md

---

changelog/content/experimental/unreleased.md
changelog/content/released/v0.2.0.md
changelog/content/released/v0.2.1.md
changelog/content/released/v0.3.0.md
changelog/content/released/v0.4.0.md
changelog/content/released/v0.4.1.md
changelog/content/released/v0.5.0.md
changelog/content/released/v0.6.0.md
changelog/content/released/v1.0.0.md
changelog/content/released/v1.1.0.md
changelog/content/released/v1.2.0.md
changelog/content/released/v1.2.1.md
changelog/content/released/v1.3.0.md
changelog/content/released/v1.4.0.md
changelog/content/released/v1.5.0.md

Relates to #951 
Relates to #952

Seperate agent & Helm releases in changelog.promitor.io

---

charts/promitor-agent-scraper/README.md
charts/promitor-agent-scraper/templates/configmap.yaml
charts/promitor-agent-scraper/values.yaml
docs/configuration/v1.x/runtime.md
docs/deployment/index.md

Provide capability to configure StatsD via Helm

---

config/grafana/dashboard-config.json
config/grafana/dashboards.yml
config/grafana/datasources.yml
config/grafana/grafana.ini
src/docker-compose.yml
src/runtime-config.yaml

Provide local Grafana configuration for StatsD

---

docs/configuration/v1.x/metrics/iot-hub.md

Fixed docs for IoT Hub - the upper case "T" was missing here

---

src/Promitor.Agents.Scraper/Extensions/IApplicationBuilderExtensions.cs
src/Promitor.Agents.Scraper/Startup.cs

Only expose when there is a URI & provide docs for legacy approach.

Only expose when there is a URI & provide docs for legacy approach

---

config/promitor/scraper/metrics.yaml
src/Promitor.Agents.Scraper/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/AzureResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/IAzureResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/ApiManagementResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/AppPlanResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/BlobStorageResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/ContainerInstanceResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/ContainerRegistryResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/CosmosDbResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/DeviceProvisioningServiceResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/FileStorageResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/FunctionAppResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/GenericAzureResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/IoTHubResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/KeyVaultResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/NetworkInterfaceResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/PostgreSqlResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/RedisCacheResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/ServiceBusQueueResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/SqlDatabaseResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/SqlManagedInstanceResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/SqlServerResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/StorageAccountResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/StorageQueueResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/VirtualMachineResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/VirtualMachineScaleSetsResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Model/Metrics/ResourceTypes/WebAppResourceDefinition.cs
src/Promitor.Integrations.Sinks.Prometheus/PrometheusScrapingEndpointMetricSink.cs

Ensure jobs have unique names to ensure all resources are scraped.
Fixes #1050

Ensure jobs have unique names to ensure all resources are scraped

---

src/Promitor.Core.Scraping/Configuration/Serialization/Deserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/FieldDeserializationInfoBuilder.cs
src/Promitor.Core.Scraping/Configuration/Serialization/IFieldDeserializationInfoBuilder.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureMetadataDeserializer.cs
src/Promitor.Tests.Unit/Serialization/FieldDeserializationInfoBuilderTests/DefaultTests.cs
src/Promitor.Tests.Unit/Serialization/FieldDeserializationInfoBuilderTests/MapUsingDeserializerTests.cs
src/Promitor.Tests.Unit/Serialization/FieldDeserializationInfoBuilderTests/MapUsingTests.cs
src/Promitor.Tests.Unit/Serialization/FieldDeserializationInfoBuilderTests/RequiredTests.cs
src/Promitor.Tests.Unit/Serialization/FieldDeserializationInfoBuilderTests/SetPropertyTests.cs
src/Promitor.Tests.Unit/Serialization/FieldDeserializationInfoBuilderTests/TestConfig.cs

I've added a new way of configuring deserializers to try to simplify things a bit, and to make it easier for us to extend deserialization. So instead of writing the following:
```csharp
MapOptional(metadata => metadata.Cloud, AzureEnvironment.AzureGlobalCloud, DetermineAzureCloud);
```
We can write it:
```csharp
Map(metadata => metadata.Cloud)
.WithDefault(AzureEnvironment.AzureGlobalCloud)
.MapUsing(DetermineAzureCloud);
```
Originally when I'd added the `MapOptional()` / `MapRequired()` methods, I wanted to avoid going too far down the route of designing a fluent interface because this is just used internally by Promitor, but the approach of using overloads becomes pretty unwieldy very quickly. Making this change makes it easier to add extra functionality to the deserializers, for …

Improve fluent mapping

---

src/Promitor.Tests.Unit/Serialization/DeserializerTests/DeserializationTests.cs
src/Promitor.Tests.Unit/Serialization/DeserializerTests/ValidationTests.cs

I've updated the tests for Deserializer to use the new `Map()` method.
Part of #1091.

Update tests to use new mapping syntax

---

src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AggregationDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureMetricConfigurationDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureResourceCollectionDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/MetricAggregationDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/MetricDefaultsDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/MetricDefinitionDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/MetricDimensionDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/ScrapingDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/SecretDeserializer.cs

I've updated all the deserializers in the core namespace to use the new mapping syntax.
Part of #1091

Update all the core deserializers

---

src/Promitor.Core.Scraping/Configuration/Serialization/Deserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/ApiManagementDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/AppPlanDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/BlobStorageDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/ContainerInstanceDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/ContainerRegistryDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/CosmosDbDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/DeviceProvisioningServiceDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/FileStorageDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/FunctionAppDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/GenericResourceDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/IoTHubDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/KeyVaultDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/NetworkInterfaceDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/PostgreSqlDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/RedisCacheDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/ResourceDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/ServiceBusQueueDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/SqlDatabaseDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/SqlManagedInstanceDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/SqlServerDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/StorageAccountDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/StorageQueueDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/VirtualMachineDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/VirtualMachineScaleSetDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/WebAppDeserializer.cs

- Updated all the resource type deserializers, switching them to the new mapping syntax.
- Removed the `MapOptional()` and `MapRequired()` methods since they aren't required anymore.
Part of #1091

Update all the resource type deserializers

---

changelog/content/experimental/unreleased.md
src/Promitor.Core.Scraping/Configuration/Providers/MetricsDeclarationProvider.cs
src/Promitor.Core.Scraping/Configuration/Serialization/DeserializationContext.cs
src/Promitor.Core.Scraping/Configuration/Serialization/Deserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/V1Deserializer.cs
src/Promitor.Core.Scraping/Promitor.Core.Scraping.csproj
src/Promitor.Tests.Unit/Promitor.Tests.Unit.csproj
src/Promitor.Tests.Unit/Serialization/DeserializationContextTests.cs
src/Promitor.Tests.Unit/Serialization/DeserializerTests/ValidationTests.cs
src/Promitor.Tests.Unit/Serialization/v1/Core/V1DeserializerTests.cs

I've updated the deserialization to provide a list of suggestions for unknown field names. This uses the Fastenshtein library to calculate the edit distance between the field name entered by a user and the possible fields.
I've chosen to return fields if they have an edit distance less than 3. This is fairly arbitrary and just based on some simple testing. I wanted to provide suggestions, but not provide ones that were completely different to the name entered.
Also:
- Updated the V1Deserializer to use the `Map()` syntax for mapping rather than doing everything manually. The main reason for this was so that the fields are added as suggestions, although it also removes some unnecessary code.
- Altered MetricsDeclarationProvider to not set the defaults if validating the metrics fails. The …

Provide possible suggestions for unknown fields

---

src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/MetricDefinitionDeserializer.cs
src/Promitor.Tests.Unit/Serialization/v1/Core/MetricDefinitionDeserializerTests.cs

I've updated the MetricDefinitionDeserializer to report a validation error if neither `resources` nor `resourceCollections` is populated.
Fixes #806
A metric definition like the following:
```yaml
- name: azure_lb_data_path_availability
description: "The CPU of our containers in a container group."
resourceType: Generic
metricName: VipAvailability
aggregation:
type: Average
```
Will now produce the following validation error:
```text
[15:56:21 ERR] The following problems were found with the metric configuration:
Error 13:5: Either 'resources' or 'resourceCollections' must be specified.
```

Report validation error if resources not specified

---

changelog/content/experimental/unreleased.md
src/Promitor.Core.Scraping/Configuration/Serialization/Deserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/FieldDeserializationContext.cs
src/Promitor.Core.Scraping/Configuration/Serialization/FieldDeserializationInfo.cs
src/Promitor.Core.Scraping/Configuration/Serialization/FieldDeserializationInfoBuilder.cs
src/Promitor.Core.Scraping/Configuration/Serialization/FieldValidators/CronExpressionValidator.cs
src/Promitor.Core.Scraping/Configuration/Serialization/FieldValidators/IFieldValidator.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/ScrapingDeserializer.cs
src/Promitor.Core.Scraping/Promitor.Core.Scraping.csproj
src/Promitor.Tests.Unit/Serialization/DeserializationContextTests.cs
src/Promitor.Tests.Unit/Serialization/DeserializerTests/ValidationTests.cs
src/Promitor.Tests.Unit/Serialization/FieldValidators/CronExpressionValidatorTests.cs

I've added the framework to perform additional validation on a field, and implemented a Cron expression validator for the scraping schedule.
Each field can have a collection of zero or more validators that implement `IFieldValidator`, and the validator uses the error reporter to report any validation errors.
Fixes #1103
If we use the following example config:
```yaml
version: v1
azureMetadata:
tenantId: <tenant-id>
subscriptionId: <subscription-id>
resourceGroupName: promitor
metricDefaults:
aggregation:
interval: 00:05:00
scraping:
schedule: "12345"
```
We'll now get the following error message:
```text
[13:24:35 ERR] The following problems were found with the metric configuration:
Error 11:15: '12345' is not a valid value for 'schedule'. The value must be a valid Cron expression.
```

Ensure that schedule is a valid Cron expression

---

changelog/content/experimental/unreleased.md
src/Promitor.Agents.Scraper/Docs/Open-Api.xml
src/Promitor.Agents.Scraper/ExitStatus.cs
src/Promitor.Agents.Scraper/Program.cs
src/Promitor.Agents.Scraper/Startup.cs
src/Promitor.Agents.Scraper/Validation/RuntimeValidator.cs

I've tweaked the way that the startup process for Promitor works so that it runs the validation in the `Main()` method. This gives us the opportunity to exit gracefully if validation fails instead of throwing an exception.
I've also added a new enum to track the possible exit statuses, and made sure that unhandled exceptions continue to use an exit code of `1`.
Fixes #1113
Here's what the output looks like with a validation error now:
```shell
[14:35:42 INF] Metrics declaration is using spec version v1
[14:35:42 INF] Starting validation of Promitor setup
[14:35:42 INF] Start Validation step 1/6: Metrics Declaration Path
[14:35:42 INF] Scrape configuration found at '/home/adam/github.com/adamconnelly/promitor/config/promitor/scraper/metrics.yaml'
[14:35:42 INF] Validation step 1/6 …
```

Exit gracefully if a validation error occurs

---

adding-a-new-scraper.md

Document how to add support for resource discovery

---

src/Promitor.Agents.Scraper/Validation/RuntimeValidator.cs
src/Promitor.Agents.Scraper/Validation/Steps/ResourceDiscoveryValidationStep.cs
src/Promitor.Tests.Integration/Services/ResourceDiscoveryTests.cs
src/Promitor.Tests.Unit/Validation/Misc/ResourceDiscoveryValidationStepTests.cs

Provide validation rule to verify if resource discovery is configured when metric discovery is used

---

src/Promitor.Agents.Core/ExitStatus.cs
src/Promitor.Agents.Core/Extensions/ConfigurationBuilderExtensions.cs
src/Promitor.Agents.Core/Extensions/ConfigurationFileNotFoundException.cs
src/Promitor.Agents.ResourceDiscovery/Program.cs
src/Promitor.Agents.Scraper/Docs/Open-Api.xml
src/Promitor.Agents.Scraper/Program.cs
src/Promitor.Tests.Unit/Agents/Core/Extensions/ConfigurationBuilder/AddRequiredYamlFileTests.cs

- Moved `ExitStatus` into the agents core and updated the discovery agent to use it.
- Updated the unhandled exception message for the discovery agent to match the format of the scraper agent.
- Added some additional validation to both agents to check that their required config files exist. This is to avoid us ending up in the unhandled exception block and directing users to create an issue.
Fixes #1113

Update discovery agent startup to match scraper

---

src/Promitor.Agents.Scraper/Validation/Steps/ResourceDiscoveryValidationStep.cs
src/Promitor.Tests.Unit/Validation/Misc/ResourceDiscoveryValidationStepTests.cs

Resource discovery is not configured, but still blocked by scraper validation.
Fixes #1196

Resource discovery is not configured, but still blocked by scraper validation

---

changelog/content/experimental/unreleased.md
config/promitor/resource-discovery/resource-discovery-declaration.yaml
config/promitor/scraper/metrics.yaml
docs/configuration/v2.x/metrics/event-hubs.md
docs/configuration/v2.x/metrics/service-bus-queue.md
docs/configuration/v2.x/resource-discovery.md
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceDiscoveryFactory.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/ServiceBusQueueDiscoveryQuery.cs
src/Promitor.Agents.Scraper/Validation/MetricDefinitions/ResourceTypes/ServiceBusQueueMetricValidator.cs
src/Promitor.Core.Contracts/ResourceTypes/ServiceBusQueueResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Mapping/V1MappingProfile.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/ServiceBusQueueDeserializer.cs
src/Promitor.Core.Scraping/ResourceTypes/AzureMessagingScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/EventHubsScraper.cs
src/Promitor.Core.Scraping/ResourceTypes/ServiceBusQueueScraper.cs
src/Promitor.Tests.Unit/Serialization/v1/Providers/ServiceBusQueueDeserializerTests.cs
src/Promitor.Tests.Unit/Validation/Metrics/ResourceTypes/ServiceBusQueueMetricsDeclarationValidationStepTests.cs

Provide capability to scrape all queues in Azure Service Bus, instead of having to declare the queue name
Fixes #529

Provide capability to scrape all queues in Azure Service Bus

---

src/Promitor.Agents.ResourceDiscovery/Graph/Query/GraphQueryBuilder.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/AppServiceResourceDiscoveryQuery.cs
src/Promitor.Agents.Scraper/Discovery/ResourceDiscoveryClient.cs
src/Promitor.Agents.Scraper/Docs/Open-Api.xml
src/Promitor.Agents.Scraper/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj
src/Promitor.Agents.Scraper/Startup.cs

- Use new library for Prometheus setup
- Fix issue with resource discovery where base address was changed multiple times
- Fix issue with resource discovery for Azure App Services / Functions

Improve resource discovery & Prometheus setup

---

config/promitor/scraper/metrics.yaml
src/Promitor.Integrations.Sinks.Prometheus/Extensions/StringExtensions.cs
src/Promitor.Integrations.Sinks.Prometheus/PrometheusScrapingEndpointMetricSink.cs
src/Promitor.Tests.Unit/Prometheus/StringExtensionTests.cs

Config:
```yaml
metrics:
- name: promitor_demo_app_insights
resourceType: Generic
metricName: dependencies/duration
dimension:
name: dependency/type
aggregation:
type: Average
resources:
- resourceUri: Microsoft.Insights/Components/docker-hub-metrics
resourceGroupName: docker-hub-metrics
```
Output:
```
promitor_demo_app_insights{resource_group="docker-hub-metrics",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/docker-hub-metrics/providers/Microsoft.Insights/Components/docker-hub-metrics",instance_name="Microsoft.Insights/Components/docker-hub-metrics",dependency_type="Http"} 500.5 1598877315829
```
Fixes #1248

Sanitize label names to comply with Prometheus requirements

---

changelog/content/experimental/unreleased.md

Dimensions with / in name are now supported by replacing it with _ for Prometheus metric sink

Dimensions with / in name are now supported by replacing it with _ for Prometheus metric sink

---

changelog/content/experimental/unreleased.md
docs/configuration/v2.x/metrics/application-gateway.md
docs/configuration/v2.x/metrics/index.md
docs/configuration/v2.x/resource-discovery.md
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceDiscoveryFactory.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/ApplicationGatewayDiscoveryQuery.cs
src/Promitor.Agents.Scraper/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Agents.Scraper/Validation/MetricDefinitions/ResourceTypes/ApplicationGatewayMetricValidator.cs
src/Promitor.Core.Contracts/ResourceType.cs
src/Promitor.Core.Contracts/ResourceTypes/ApplicationGatewayResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureResourceDeserializerFactory.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Mapping/V1MappingProfile.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/ResourceTypes/ApplicationGatewayResourceV1.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/ApplicationGatewayDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/ApplicationGatewayScraper.cs
src/Promitor.Tests.Unit/Builders/Metrics/v1/MetricsDeclarationBuilder.cs
src/Promitor.Tests.Unit/Serialization/v1/Providers/ApplicationGatewayDeserializerTests.cs
src/Promitor.Tests.Unit/Validation/Scraper/Metrics/ResourceTypes/ApplicationGatewayMetricsDeclarationValidationStepsTests.cs

Provide support for scraping Azure Application Gateway
Fixes #313
Metrics output:
```
azure_application_gateway_milli_total_time{resource_group="RG",subscription_id="SID",resource_uri="subscriptions/SID/resourceGroups/RG/providers/Microsoft.Network/applicationGateways/AG",instance_name="AG"} 8 1599050691198
promitor_ratelimit_arm{tenant_id="TID",subscription_id="SID",app_id="APPID"} 11998 1599050690955
```
Discovery output:
`[{"$type":"Promitor.Core.Contracts.ResourceTypes.ApplicationGatewayResourceDefinition, Promitor.Core.Contracts","ApplicationGatewayName":"AG","ResourceType":"ApplicationGateway","SubscriptionId":"SID","ResourceGroupName":"RG","ResourceName":"AG","UniqueName":"AG"}]`

Provide support for scraping Azure Application Gateway

---

build/azure-devops/agents-ci-discovery.yml
build/azure-devops/agents-ci-scraper.yml
build/azure-devops/templates/helm/lint-chart.yml
build/azure-devops/templates/helm/package-preview-chart.yml
build/azure-devops/templates/stages/helm-chart-verification.yml
build/helm/Transform-Chart.ps1
charts/promitor-agent-resource-discovery/.helmignore
charts/promitor-agent-resource-discovery/Chart.yaml
charts/promitor-agent-resource-discovery/LICENSE
charts/promitor-agent-resource-discovery/README.md
charts/promitor-agent-resource-discovery/templates/NOTES.txt
charts/promitor-agent-resource-discovery/templates/_helpers.tpl
charts/promitor-agent-resource-discovery/templates/configmap.yaml
charts/promitor-agent-resource-discovery/templates/deployment.yaml
charts/promitor-agent-resource-discovery/templates/podsecuritypolicy.yaml
charts/promitor-agent-resource-discovery/templates/role.yaml
charts/promitor-agent-resource-discovery/templates/rolebinding.yaml
charts/promitor-agent-resource-discovery/templates/secret.yaml
charts/promitor-agent-resource-discovery/templates/service.yaml
charts/promitor-agent-resource-discovery/templates/serviceaccount.yaml
charts/promitor-agent-resource-discovery/values.yaml

Provide boilerplate for Resource Discovery Helm chart

---

docs/concepts/how-it-works.md
docs/configuration/v2.x/metrics/index.md
docs/index.md

General documentation improvements for resource discovery

---

changelog/content/experimental/unreleased.md
charts/promitor-agent-resource-discovery/README.md
charts/promitor-agent-resource-discovery/templates/deployment.yaml
charts/promitor-agent-resource-discovery/values.yaml
charts/promitor-agent-scraper/README.md
charts/promitor-agent-scraper/templates/deployment.yaml
charts/promitor-agent-scraper/values.yaml

Provide capability to tweak liveness/readines probes

---

changelog/content/experimental/unreleased.md
src/Promitor.Agents.Core/Extensions/IApplicationBuilderExtensions.cs
src/Promitor.Agents.Core/HttpHeaders.cs
src/Promitor.Agents.Core/Middleware/AgentVersionMiddleware.cs
src/Promitor.Agents.ResourceDiscovery/Startup.cs
src/Promitor.Agents.Scraper/Startup.cs
src/Promitor.Tests.Integration/Services/ResourceDiscovery/HealthTests.cs
src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceCollectionTests.cs
src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryIntegrationTest.cs
src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs
src/Promitor.Tests.Integration/Services/ResourceDiscovery/SystemTests.cs
src/Promitor.Tests.Integration/Services/Scraper/HealthTests.cs
src/Promitor.Tests.Integration/Services/Scraper/ScraperIntegrationTest.cs
src/Promitor.Tests.Integration/Services/Scraper/SystemTests.cs

Provide `X-Version` response header for API endpoints

---

changelog/content/experimental/unreleased.md
config/prometheus/prometheus.yml
docs/configuration/v2.x/runtime/scraper.md
docs/faq.md
src/Promitor.Core.Scraping/AzureMonitorScraper.cs
src/Promitor.Core/Metrics/MeasuredMetric.cs
src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs
src/Promitor.Integrations.AzureMonitor/Exceptions/MetricInformationNotFoundException.cs

fix: Metrics without a timeseries are not reported with the `metricSinks.prometheusScrapingEndpoint.metricUnavailableValue`
Fixes #1197
```
azure_event_hubs_incoming_messages_discovery{resource_group="promitor-sources",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor-sources/providers/Microsoft.EventHub/namespaces/promitor-streaming",instance_name="promitor-streaming",entity_name="topic-1"} 1 1606049042395
```
For the other dimension that does not have a value triggered an exception:
> [12:44:02 FTL] Failed to scrape resource for metric 'azure_event_hubs_incoming_messages_discovery'
Promitor.Integrations.AzureMonitor.Exceptions.MetricInformationNotFoundException: No metric information was found …

fix: Metrics without a timeseries are not reported

---

changelog/content/experimental/unreleased.md
docs/configuration/v2.x/metrics/event-hubs.md
docs/configuration/v2.x/metrics/service-bus-queue.md
src/Promitor.Agents.Scraper/Validation/MetricDefinitions/ResourceTypes/EventHubsMetricValidator.cs
src/Promitor.Agents.Scraper/Validation/MetricDefinitions/ResourceTypes/ServiceBusQueueMetricValidator.cs
src/Promitor.Tests.Unit/Validation/Scraper/Metrics/ResourceTypes/EventHubsMetricsDeclarationValidationStepTests.cs
src/Promitor.Tests.Unit/Validation/Scraper/Metrics/ResourceTypes/ServiceBusQueueMetricsDeclarationValidationStepTests.cs

feat: Allow `EntityPath` as a dimension for Service Bus metrics #808

---

docs/faq.md

docs: Document how Promitor handles removed resources

---

docs/deployment/scraper/index.md
docs/index.md

docs: Publish for 2.0.0-rc

---

src/Promitor.Agents.Core/Extensions/IApplicationBuilderExtensions.cs
src/Promitor.Agents.Scraper/Startup.cs

fix: OpenAPI docs are not rendered correctly when using a URL prefix

---

src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs

Align test expectations with Azure subscription after subscription cleanup.

fix: Align test expectations with Azure subscription

---

build/azure-devops/agents-resource-discovery-release-official.yml
build/azure-devops/agents-scraper-release-official.yml

docs: Refer to GitHub Container Registry for releases

---

renovate.json

Remove rebase option from Renovate to use auto-merge.

chore: Remove rebase option from Renovate

---

config/promitor/scraper/contrib/README.md
config/promitor/scraper/contrib/cosmosdb.yaml
config/promitor/scraper/contrib/keyvault.yaml
config/promitor/scraper/contrib/storage-blob.yaml
config/promitor/scraper/contrib/vmss.yaml

Adds starter configuration files for Azure resources:
- Cosmos DB usage, RUs consumption, latency and availability metrics
- Key Vault latency, saturation and availability metrics
- Blob Storage API requests, data, latency and availability metrics
- Virtual Machine Scale Set (VMSS) CPU, disk and network usage metrics

Starter scraper config for Azure resources

---

changelog/content/experimental/unreleased.md
config/promitor/resource-discovery/resource-discovery-declaration.yaml
config/promitor/scraper/metrics.yaml
docs/configuration/v2.x/metrics/front-door.md
docs/configuration/v2.x/metrics/index.md
docs/configuration/v2.x/resource-discovery.md
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceDiscoveryFactory.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/FrontDoorDiscoveryQuery.cs
src/Promitor.Agents.Scraper/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Agents.Scraper/Validation/MetricDefinitions/ResourceTypes/FrontDoorMetricValidator.cs
src/Promitor.Core.Contracts/ResourceType.cs
src/Promitor.Core.Contracts/ResourceTypes/FrontDoorResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureResourceDeserializerFactory.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Mapping/V1MappingProfile.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/ResourceTypes/FrontDoorResourceV1.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/FrontDoorDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/FrontDoorScraper.cs
src/Promitor.Tests.Unit/Builders/Metrics/v1/MetricsDeclarationBuilder.cs
src/Promitor.Tests.Unit/Serialization/v1/Providers/FrontDoorDeserializerTests.cs
src/Promitor.Tests.Unit/Validation/Scraper/Metrics/ResourceTypes/FrontDoorMetricsDeclarationValidationStepsTests.cs

When implementing a new scraper; these tasks are completed:
**Metrics output:**
```
promitor_demo_frontdoor_backend_health_per_backend{resource_group="promitor-landscape",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor-landscape/providers/Microsoft.Network/frontdoors/promitor-landscape",instance_name="promitor-landscape",backend="promitor.io:443",app="promitor"} 100 1612809662196
promitor_demo_frontdoor_backend_health_per_backend_pool{resource_group="promitor-landscape",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor-landscape/providers/Microsoft.Network/frontdoors/promitor-landscape",instance_name="p …
```

feat: Provide Azure Front Door scraper 

---

.github/ISSUE_TEMPLATE/1_feature_request.yml
.github/ISSUE_TEMPLATE/1_feature_request_legacy.yml
.github/ISSUE_TEMPLATE/2_bug_report.yml
.github/ISSUE_TEMPLATE/2_bug_report_legacy.yml
.github/ISSUE_TEMPLATE/3_security_issue.yml
.github/ISSUE_TEMPLATE/3_security_issue_legacy.yml
.github/ISSUE_TEMPLATE/config.yml

Migrate to new Issue Forms YAML spec as per https://gh-community.github.io/issue-template-feedback/changes/ which is taking affect tomorrow.

chore: Migrate to new Issue Forms YAML spec

---

changelog/content/experimental/unreleased.md
config/promitor/scraper/metrics.yaml
docs/configuration/v1.x/metrics/index.md
docs/configuration/v2.x/metrics/index.md
src/Promitor.Core.Scraping/Configuration/Model/MetricDefaults.cs
src/Promitor.Core.Scraping/Configuration/Providers/Interfaces/IMetricsDeclarationProvider.cs
src/Promitor.Core.Scraping/Configuration/Providers/MetricsDeclarationProvider.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/MetricDefaultsDeserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/MetricDefaultsV1.cs
src/Promitor.Integrations.Sinks.Prometheus/PrometheusScrapingEndpointMetricSink.cs
src/Promitor.Tests.Unit/Metrics/Sinks/PrometheusScrapingEndpointMetricSinkTests.cs
src/Promitor.Tests.Unit/Serialization/v1/V1SerializationTests.cs

Fixes #1608
Assuming this configuration:
```yaml
version: v1
azureMetadata:
tenantId: c8819874-9e56-4e3f-b1a8-1c0325138f27
subscriptionId: 0f9d7fea-99e8-4768-8672-06a28514f77e
resourceGroupName: promitor
metricDefaults:
aggregation:
interval: 00:05:00
labels:
geo: china
environment: dev
scraping:
schedule: "0 * * ? * *"
metrics:
- name: promitor_demo_function_memory_discovery
description: "Average memory for an Azure Function App"
resourceType: FunctionApp
metricName: MemoryWorkingSet
aggregation:
type: Average
resourceDiscoveryGroups:
- name: function-app-landscape
- name: promitor_demo_servicebus_messagecount_discovered
description: "Average percentage of memory usage on an Azure App Plan"
resourceType: ServiceBusNamespace
labels:
geo: europe
app: promitor …
```

feat: Provide capability to define default custom labels 

---

changelog/content/experimental/unreleased.md
config/promitor/resource-discovery/resource-discovery-declaration.yaml
config/promitor/scraper/metrics.yaml
docs/configuration/v2.x/metrics/index.md
docs/configuration/v2.x/metrics/monitor-autoscale.md
docs/configuration/v2.x/resource-discovery.md
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceDiscoveryFactory.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/MonitorAutoscaleDiscoveryQuery.cs
src/Promitor.Agents.Scraper/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Agents.Scraper/Validation/MetricDefinitions/ResourceTypes/MonitorAutoscaleMetricValidator.cs
src/Promitor.Core.Contracts/ResourceType.cs
src/Promitor.Core.Contracts/ResourceTypes/MonitorAutoscaleResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureResourceDeserializerFactory.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Mapping/V1MappingProfile.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/ResourceTypes/MonitorAutoscaleResourceV1.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/MonitorAutoscaleDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/MonitorAutoscaleScraper.cs
src/Promitor.Tests.Unit/Builders/Metrics/v1/MetricsDeclarationBuilder.cs
src/Promitor.Tests.Unit/Serialization/v1/Providers/MonitorAutoscaleDeserializerTests.cs
src/Promitor.Tests.Unit/Validation/Scraper/Metrics/ResourceTypes/MonitorAutoscaleMetricsDeclarationValidationStepsTests.cs
src/Promitor.sln.DotSettings

When implementing a new scraper; these tasks are completed:
**Metrics output:**
```
promitor_demo_appplan_autoscale_actions_scale{resource_group="demo",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/demo/providers/Microsoft.Insights/autoscalesettings/app-service-autoscaling-rules",instance_name="app-service-autoscaling-rules",scaledirection="Increase",app="promitor",geo="china",environment="dev"} 0 1620294180665
promitor_demo_appplan_autoscale_instances_current{resource_group="demo",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/demo/providers/Microsoft.Insights/au …
```

feat: Provide scraper for Azure Monitor Autoscale

---

src/Promitor.Agents.ResourceDiscovery/Graph/AzureResourceGraph.cs
src/Promitor.Core/Extensions/AzureCloudExtensions.cs
src/Promitor.Core/Promitor.Core.csproj
src/Promitor.Integrations.Azure/Authentication/AzureAuthenticationFactory.cs
src/Promitor.Tests.Unit/Azure/AzureCloudUnitTests.cs

Relates to https://github.com/tomkerkhove/promitor/issues/1646
This PR fixes 2 parts:
- First one is adding the AuthorityHost for the TokenCredentialOptions, since this value will be different for each Cloud
- Second one is similar to the first but with the ResourceGraphClient which will need the baseUri of the Managment Resource Endpoint

fix: missing authority host param and resource management endpoint when init the client

---

changelog/content/experimental/unreleased.md

Document fix for authenticating to Azure clouds other than public

---

src/Promitor.Tests.Integration/Services/ResourceDiscovery/ResourceDiscoveryTests.cs

Signed-off-by: GitHub <noreply@github.com>
Fixes #

chore: Align test expectations with Azure subscription

---

src/Promitor.Core.Scraping/Scraper.cs

Provide correct resource group name for runtime metric labels so that they are always reported correctly.
Relates to #1304

fix: Provide correct resource group name for runtime metric labels

---

build/azure-devops/agents-ci-discovery.yml
build/azure-devops/agents-ci-scraper.yml
build/azure-devops/agents-resource-discovery-release-official.yml
build/azure-devops/agents-scraper-release-official.yml
build/azure-devops/docs-ci.yml

Use ubuntu-latest instead of pinning to Ubuntu 16 for Azure Pipelines which are deprecated.
Relates to https://github.com/actions/virtual-environments/issues/3287

chore: Use ubuntu-latest instead of pinning to Ubuntu 16 for Azure Pipelines

---

changelog/content/experimental/unreleased.md
docs/operations/index.md
src/Promitor.Agents.ResourceDiscovery/Scheduling/AzureLandscapeDiscoveryBackgroundJob.cs

Provide changelog & docs for new runtime metrics
Relates to #1717 
Closes #341

docs: Provide changelog & docs for new runtime metrics

---

src/Promitor.Tests.Unit/Builders/Queries/GraphQueryBuilderTests.cs

test: Add unit tests for Graph Query Builder

---

changelog/content/experimental/unreleased.md
docs/operations/index.md
src/Promitor.Agents.Core/RequestHandlers/ThrottlingRequestHandler.cs
src/Promitor.Agents.ResourceDiscovery/Docs/Open-Api.xml
src/Promitor.Agents.ResourceDiscovery/Graph/AzureResourceGraph.cs
src/Promitor.Agents.ResourceDiscovery/Graph/RequestHandlers/AzureResourceGraphThrottlingRequestHandler.cs
src/Promitor.Agents.ResourceDiscovery/Scheduling/AzureResourceGroupsDiscoveryBackgroundJob.cs
src/Promitor.Agents.ResourceDiscovery/Scheduling/AzureSubscriptionDiscoveryBackgroundJob.cs
src/Promitor.Agents.ResourceDiscovery/Scheduling/DiscoveryBackgroundJob.cs
src/Promitor.Core/Extensions/AzureEnvironmentExtensions.cs
src/Promitor.Core/Metrics/Prometheus/Collectors/Interfaces/IAzureScrapingPrometheusMetricsCollector.cs
src/Promitor.Core/Promitor.Core.csproj
src/Promitor.Core/RuntimeMetricNames.cs
src/Promitor.Integrations.AzureMonitor/RequestHandlers/AzureResourceManagerThrottlingRequestHandler.cs
src/Promitor.Integrations.Sinks.Prometheus/Collectors/AzureScrapingPrometheusMetricsCollector.cs
src/Promitor.Tests.Integration/Services/ResourceDiscovery/PrometheusSystemMetricsTests.cs
src/Promitor.Tests.Integration/Services/Scraper/MetricSinks/PrometheusSystemMetricsTests.cs
src/Promitor.Tests.Unit/Azure/AzureEnvironmentUnitTests.cs

Provide Azure Resource Graph rate limiting info & throttling status metrics
**Scraper output:**
```text
promitor_ratelimit_arm{tenant_id="c8819874-9e56-4e3f-b1a8-1c0325138f27",subscription_id="0329dd2a-59dc-4493-aa54-cb01cb027dc2",app_id="ceb249a3-44ce-4c90-8863-6776336f5b7e"} 11995 1629719527020
promitor_ratelimit_arm{tenant_id="c8819874-9e56-4e3f-b1a8-1c0325138f27",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",app_id="ceb249a3-44ce-4c90-8863-6776336f5b7e"} 11989 1629719532626
promitor_ratelimit_arm_throttled{tenant_id="c8819874-9e56-4e3f-b1a8-1c0325138f27",subscription_id="0329dd2a-59dc-4493-aa54-cb01cb027dc2",app_id="ceb249a3-44ce-4c90-8863-6776336f5b7e"} 0 1629719527020
promitor_ratelimit_arm_throttled{tenant_id="c8819874-9e56-4e3f-b1a8-1c0325138f27",subscription_id="0f9d7fea- …
```

feat: Provide Azure Resource Graph rate limiting info & throttling status metrics

---

docs/configuration/v2.x/runtime/scraper.md

Document how to enable resource discovery with `resourceDiscovery.enabled: true` in Scraper agent.
Fixes #1495

docs: Document how to enable resource discovery in Scraper agent

---

docs/configuration/v2.x/runtime/scraper.md

Just a small typo fix for the name of the metric sink.

docs: resolve a typo in the metric sink docs

---

CONTRIBUTING.md
README.md
adding-a-new-scraper.md

docs: Rename developer guide to contribution guide & document changelog

---

changelog/content/experimental/unreleased.md
src/Promitor.Agents.Core/RequestHandlers/ThrottlingRequestHandler.cs
src/Promitor.Agents.Scraper/AzureMonitorClientFactory.cs
src/Promitor.Agents.Scraper/Docs/Open-Api.xml
src/Promitor.Agents.Scraper/Scheduling/ResourceDiscoveryGroupScrapingJob.cs
src/Promitor.Agents.Scraper/Scheduling/SchedulingExtensions.cs
src/Promitor.Agents.Scraper/Startup.cs
src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs

Reduce the number of API calls to retrieve metric definitions through caching.
Fixes  #1914

fix: Reduce the number of API calls to retrieve metric definitions through caching

---

docs/configuration/v2.x/metrics/synapse-workspace.md

Fix typo in Azure Synapse (Workspace) doc (wrong name for resource discovery group)

fix: typo in Azure Synapse (Workspace) doc

---

docs/configuration/v2.x/metrics/generic-azure-resource.md

- Highlight the fact that the filter parameter is optional.
- Inform people about the filter syntax.
- Inform people about the other optional fields available.
Fixes #1740
Fixes #1849.

docs: Update Generic scraper doc

---

changelog/content/experimental/unreleased.md
src/Promitor.Core/Metrics/Prometheus/Collectors/PrometheusMetricsCollector.cs
src/Promitor.sln

fix: Honor flag not to include timestamps in system metrics for Prometheus

---

changelog/content/experimental/unreleased.md
src/Promitor.Agents.ResourceDiscovery/Scheduling/AzureResourceGroupsDiscoveryBackgroundJob.cs
src/Promitor.Agents.ResourceDiscovery/Scheduling/AzureSubscriptionDiscoveryBackgroundJob.cs

Correct paging issue when fetching resources from Azure resource discovery.
Fixes #2018

fix: Ensure Resource Discovery increments current page to reduce CPU usage

---

.github/workflows/ci-code.yml

Relates to https://github.com/tomkerkhove/promitor/issues/2053
Being tested in https://github.com/tomkerkhove/promitor/pull/2054

ci: Assign permissions for unit tests to be reported.

---

src/Promitor.Agents.ResourceDiscovery/Graph/Query/GraphQueryBuilder.cs
src/Promitor.Agents.ResourceDiscovery/Graph/Repositories/AzureResourceRepository.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceDiscoveryQuery.cs

Address possible issues when queries span multiple pages due to missing deterministic sort. 
Graph queries will now be made with an "order by" clause to provide deterministic sorting and therefore result ordering suitable for pagination.

fix: Added Order By to Graph Queries

---

changelog/content/experimental/unreleased.md
changelog/content/released/v0.8.0-resource-discovery.md
changelog/content/released/v2.7.0-scraper.md

docs: List new releases in changelog

---

renovate.json

Combine update all Prometheus.Client packages into one PR

chore(deps): Add group for Prometheus.Client in Renovate config

---

src/Promitor.Agents.Scraper/Discovery/Interfaces/IResourceDiscoveryRepository.cs
src/Promitor.Agents.Scraper/Discovery/ResourceDiscoveryRepository.cs
src/Promitor.Agents.Scraper/Discovery/StubResourceDiscoveryRepository.cs
src/Promitor.Agents.Scraper/Docs/Open-Api.xml
src/Promitor.Agents.Scraper/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Agents.Scraper/Health/ResourceDiscoveryHealthCheck.cs
src/Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj
src/Promitor.Agents.Scraper/Scheduling/ResourcesScrapingJob.cs
src/Promitor.Agents.Scraper/Scheduling/SchedulingExtensions.cs
src/Promitor.Agents.Scraper/Startup.cs

fix: Ensure scraper works without resource discovery

---

src/Promitor.Tests.Unit/Agents/ResourceDiscovery/AzureResourceGroupsDiscoveryBackgroundJobTests.cs

Fixes #2052 by providing unit tests for AzureResourceGroupsDiscoveryBackgroundJob

 test(resource-discovery): Provide unit tests for AzureResourceGroupsDiscoveryBackgroundJob

---

changelog/content/experimental/unreleased.md
src/Promitor.Agents.Scraper/Scheduling/SchedulingExtensions.cs

Don't schedule scraping jobs when metrics are misconfigured, otherwise the following exception will be thrown:
```
█████╗ ██████╗ ██████╗ 
██╔══██╗██╔══██╗██╔═══██╗████╗ ████║██║╚══██╔══╝██╔═══██╗██╔══██╗
██████╔╝██████╔╝██║   ██║██╔████╔██║██║   ██║   ██║   ██║██████╔╝
██╔═══╝ ██╔══██╗██║   ██║██║╚██╔╝██║██║   ██║   ██║   ██║██╔══██╗
██║     ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║   ██║   ╚██████╔╝██║  ██║
╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝
[09:14:39 INF] Booting up Promitor v1.0.0 running .NET .NET 6.0.10 - Thank you for using Promitor!
[09:14:39 INF] Running .NET 6.0.10 on Linux (alpine.3.16-x64 | Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022).
[09:14:39 INF] Using configuration folder '/config/'
[09:14:41 INF] The following metric …
```

fix: Don't schedule scraping jobs when metrics are misconfigured

---

src/Promitor.Integrations.Sinks.Statsd/StatsdMetricSink.cs
src/Promitor.Tests.Unit/Metrics/Sinks/StatsDMetricSinkTests.cs

…the numbers.
Fixes #
Fix an issue with Geneva MDM container for StatsDSink.

fix: Geneva MDM does not supporting doubles (#2223)Co-authored-by: Sagi Vaknin <sagivaknin@microsoft.com>

---

changelog/content/experimental/unreleased.md
src/Promitor.Agents.Scraper/Docs/Open-Api.xml
src/Promitor.Agents.Scraper/Extensions/IApplicationBuilderExtensions.cs
src/Promitor.Agents.Scraper/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Agents.Scraper/Startup.cs

```diff
- otel_azure_container_instance_cpu_usage_discovered{app="promitor",instance="15cdf614-d987-4fbb-b6f5-1df5cc071ac9",instance_name="promitor-testing-resource-eu-aci",job="unknown_service:dotnet",resource_group="promitor-testing-infrastructure-europe",resource_uri="subscriptions/63c590b6-4947-4898-92a3-cae91a31b5e4/resourceGroups/promitor-testing-infrastructure-europe/providers/Microsoft.ContainerInstance/containerGroups/promitor-testing-resource-eu-aci",subscription_id="63c590b6-4947-4898-92a3-cae91a31b5e4"} 0 1677336928582
+ otel_azure_container_instance_cpu_usage_discovered{app="promitor",instance="15cdf614-d987-4fbb-b6f5-1df5cc071ac9",instance_name="promitor-testing-resource-eu-aci",job="promitor-scraper",resource_group="promitor-testing-infrastructure-europe",resource_uri="subsc …
```

fix(otel): Provide correct job name in OpenTelemetry Collector

---

src/Promitor.Agents.Core/AgentStartup.cs
src/Promitor.Agents.Core/Promitor.Agents.Core.csproj
src/Promitor.Agents.ResourceDiscovery/Graph/Repositories/AzureResourceRepository.cs
src/Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj
src/Promitor.Agents.Scraper/Discovery/ResourceDiscoveryClient.cs
src/Promitor.Agents.Scraper/Extensions/IServiceCollectionExtensions.cs
src/Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj
src/Promitor.Integrations.Sinks.OpenTelemetry/Promitor.Integrations.Sinks.OpenTelemetry.csproj
src/Promitor.Tests.Integration/Clients/AgentClient.cs
src/Promitor.Tests.Integration/Clients/PrometheusClient.cs
src/Promitor.Tests.Integration/Promitor.Tests.Integration.csproj
src/Promitor.Tests.Unit/Metrics/Sinks/PrometheusScrapingEndpointMetricSinkTests.cs
src/Promitor.Tests.Unit/Promitor.Tests.Unit.csproj

chore(deps): Bump dependencies

---

changelog/content/experimental/unreleased.md
config/promitor/resource-discovery/resource-discovery-declaration.yaml
config/promitor/scraper/metrics.yaml
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceDiscoveryFactory.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/TrafficManagerDiscoveryQuery.cs
src/Promitor.Agents.Scraper/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Agents.Scraper/Validation/MetricDefinitions/ResourceTypes/TrafficManagerMetricValidator.cs
src/Promitor.Core.Contracts/ResourceType.cs
src/Promitor.Core.Contracts/ResourceTypes/TrafficManagerResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureResourceDeserializerFactory.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Mapping/V1MappingProfile.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/ResourceTypes/TrafficManagerResourceV1.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/TrafficManagerDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/TrafficManagerScraper.cs
src/Promitor.Tests.Unit/Builders/Metrics/v1/MetricsDeclarationBuilder.cs
src/Promitor.Tests.Unit/Serialization/v1/Providers/TrafficManagerDeserializerTests.cs
src/Promitor.Tests.Unit/Validation/Scraper/Metrics/ResourceTypes/TrafficManagerMetricsDeclarationValidationStepTests.cs

Picking this up from where the original author left off
When implementing a new scraper; these tasks are completed:
**Metrics output:**
```
azure_traffic_manager_endpoint_qps{tenant_id="<tenant_id>",subscription_id="<subscription_id>",resource_uri="<resource_uri>",resource_group="<resource_group>",instance_name="<instance_name>",geo="china",environment="dev"} 1781 1679494981881
```
**Discovery output:**
```json
{"MetricName": "Discovered Resources", "MetricValue": 15, "Timestamp": "2023-03-22T14:20:38.6195166 +00:00", "Context": {"ResourceType": "TrafficManager", "CollectionName": "traffic-managers", "TelemetryType": "Metrics"}, "$type": "MetricLogEntry"}
```
Fixes #2192
Fixed #376
Related to #2194

feat: Support Azure Traffic Manager Profiles

---

.github/workflows/publish-ci-test-report.yml

test: Simplify downloading artifact

---

changelog/content/experimental/unreleased.md
src/Promitor.Agents.ResourceDiscovery/Dockerfile.linux
src/Promitor.Agents.Scraper/Dockerfile.linux

Related to #2328
Related to #2326
For installing the ICU libraries, I followed the pattern used by .NET to install the .NET runtime dependencies in their distroless images.

feat: switch to Mariner distroless base images

---

build/azure-devops/agents-ci-scraper.yml
build/azure-devops/variables/tests.yml

test: Show OpenTelemetry metrics in Prometheus endpoint

---

changelog/content/experimental/unreleased.md
src/Promitor.Core.Scraping/AzureMonitorScraper.cs
src/Promitor.Core/Metrics/Exceptions/MissingDimensionException.cs
src/Promitor.Core/Metrics/MeasuredMetric.cs
src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs
src/Promitor.Tests.Unit/Metrics/MeasuredMetricTests.cs

Fixes #2331
At Axon, we observed that Azure Monitor may, from time to time, return time series without the requested dimension. The previous try catch logic is at the metric level, ensuring that failure to scrape one metric will not affect all metrics; however, there are many time series within a metric, and failure to process one time series will result in a metric gap for that metric. I am adding a try-catch when looping over time series to prevent that from happening. 
I am very new to this repo though, and couldn't find my way around how to write tests for this. Some help would be much appreciated.

fix: Improve AzureMonitorScraper Error Handling for Time Series Missing Requested Dimension Value

---

src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs

Hey Tom, this is to fix the mistake I made in this now merged [PR](https://github.com/tomkerkhove/promitor/pull/2345). I accidentally let a desired change get overwritten while merging master. This is the bad merge commit in question: [bad delta](https://github.com/tomkerkhove/promitor/pull/2345/commits/871103880de0f17e29493a1b2a42b16d76019a87#diff-61be23da435b37e5cff41774f451bb2f1dca8e09a1d32a41a3cbafeb2f76f4f0L113). I don't believe this bad merge will cause any regression, thankfully. It just invalidates the intended fix. 
I saw that my merged PR made it to the most recent release. I think this also means you may need to delete it and re-lease a new version? 
I am really sorry about my mistake and any trouble it may have caused!

fix: add back try catch for MissingDimensionException(removed due to bad merge) 

---

src/Promitor.Tests.Unit/Promitor.Tests.Unit.csproj

Fixes #
Nexus IQ scan has detected a critical vulnerability on the latest version of Moq i.e. v4.20.70. Hence reverting it until the vulnerability has been fixed.
Hence reverting it to v4.18.4.

fix(deps): update dependency Moq to earlier version that is not flagged

---

.github/workflows/templates-build-push-image.yml
src/Promitor.Agents.Scraper/AzureMonitorClientFactory.cs
src/Promitor.Agents.Scraper/Docs/Open-Api.xml
src/Promitor.Agents.Scraper/Scheduling/ResourcesScrapingJob.cs
src/Promitor.Core.Scraping/Configuration/Model/MetricsDeclaration.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/V1Deserializer.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/MetricsDeclarationV1.cs
src/Promitor.Integrations.AzureMonitor/Configuration/AzureMonitorIntegrationConfiguration.cs
src/Promitor.Integrations.AzureMonitor/LegacyAzureMonitorClient.cs
src/Promitor.Tests.Unit/Configuration/RuntimeConfigurationUnitTest.cs
src/Promitor.Tests.Unit/Generators/Config/RuntimeConfigurationGenerator.cs
src/Promitor.Tests.Unit/Serialization/v1/Core/V1DeserializerTests.cs

Per our discussion here: https://github.com/promitor/docs/pull/62#discussion_r1615184565

refactor: Move Azure Monitor SDK Feature Flag to Runtime Configuration 

---

build/azure-devops/templates/agents/run-opentelemetry-collector.yml
changelog/content/experimental/unreleased.md
config/promitor/resource-discovery/resource-discovery-declaration.yaml
config/promitor/scraper/metrics.yaml
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceDiscoveryFactory.cs
src/Promitor.Agents.ResourceDiscovery/Graph/ResourceTypes/AzureFirewallDiscoveryQuery.cs
src/Promitor.Agents.Scraper/Validation/Factories/MetricValidatorFactory.cs
src/Promitor.Agents.Scraper/Validation/MetricDefinitions/ResourceTypes/AzureFirewallMetricValidator.cs
src/Promitor.Core.Contracts/ResourceType.cs
src/Promitor.Core.Contracts/ResourceTypes/AzureFirewallDefinition.cs
src/Promitor.Core.Contracts/ResourceTypes/AzureFirewallResourceDefinition.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureResourceDeserializerFactory.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Mapping/V1MappingProfile.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Model/ResourceTypes/AzureFirewallResourceV1.cs
src/Promitor.Core.Scraping/Configuration/Serialization/v1/Providers/AzureFirewallDeserializer.cs
src/Promitor.Core.Scraping/Factories/MetricScraperFactory.cs
src/Promitor.Core.Scraping/ResourceTypes/AzureFirewallScraper.cs
src/Promitor.Tests.Unit/Builders/Metrics/v1/MetricsDeclarationBuilder.cs
src/Promitor.Tests.Unit/Serialization/v1/Providers/AzureFirewallDeserializerTests.cs
src/Promitor.Tests.Unit/Validation/Scraper/Metrics/ResourceTypes/AzureFirewallDeclarationValidationStepsTests.cs

When implementing a new scraper; these tasks are completed:
**Metrics output:**
```
azure_firewall_application_rule_hits{tenant_id="<redacted>",subscription_id="<redacted>",status="unknown",resource_uri="subscriptions/<redacted>/resourceGroups/<redacted>-vnet/providers/Microsoft.Network/azureFirewalls/<redacted>-firewall",resource_group="<redacted>-vnet",instance_name="<redacted>-firewall"} NaN 1726675946568
azure_firewall_application_rule_hits{tenant_id="<redacted>",subscription_id="<redacted>b",status="Allow",resource_uri="subscriptions/<redacted>/resourceGroups/<redacted>-vnet/providers/Microsoft.Network/azureFirewalls/<redacted>-firewall",resource_group="<redacted>-vnet",instance_name="<redacted>-firewall"} 84 1726675946630
azure_firewall_application_rule_hits{tenant_id="<redacted>",su …
```

feat: Provide support for Azure Firewall

---

.github/workflows/ci-code.yml

chore: Update muno92/resharper_inspectcode to 1.12.4

---

src/Promitor.Agents.ResourceDiscovery/Dockerfile.linux
src/Promitor.Agents.Scraper/Dockerfile.linux

chore: upgrade Linux base image version

---

.github/workflows/templates-build-push-image.yml
changelog/content/experimental/unreleased.md
src/Promitor.Agents.Core/Configuration/Defaults.cs
src/Promitor.Agents.Scraper/Scheduling/ResourcesScrapingJob.cs

fix: correctly log job timeout 

---

config/promitor/resource-discovery/resource-discovery-declaration.yaml
config/promitor/resource-discovery/runtime.yaml
config/promitor/scraper/metrics.yaml
config/promitor/scraper/runtime.yaml

chore(ci): update tenant configuration for GitHub Actions and PR Gates

---

build/azure-devops/variables/build.yml
src/Promitor.Agents.Core/Promitor.Agents.Core.csproj
src/Promitor.Agents.ResourceDiscovery/Dockerfile.linux
src/Promitor.Agents.ResourceDiscovery/Dockerfile.windows
src/Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj
src/Promitor.Agents.Scraper/Dockerfile.linux
src/Promitor.Agents.Scraper/Dockerfile.windows
src/Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj
src/Promitor.Core.Contracts/Promitor.Core.Contracts.csproj
src/Promitor.Core.Scraping/Promitor.Core.Scraping.csproj
src/Promitor.Core.Telemetry/Promitor.Core.Telemetry.csproj
src/Promitor.Core/Promitor.Core.csproj
src/Promitor.Integrations.Azure/Promitor.Integrations.Azure.csproj
src/Promitor.Integrations.AzureMonitor/Promitor.Integrations.AzureMonitor.csproj
src/Promitor.Integrations.AzureStorage/Promitor.Integrations.AzureStorage.csproj
src/Promitor.Integrations.LogAnalytics/Promitor.Integrations.LogAnalytics.csproj
src/Promitor.Integrations.Sinks.Atlassian.Statuspage/Promitor.Integrations.Sinks.Atlassian.Statuspage.csproj
src/Promitor.Integrations.Sinks.Core/Promitor.Integrations.Sinks.Core.csproj
src/Promitor.Integrations.Sinks.OpenTelemetry/Promitor.Integrations.Sinks.OpenTelemetry.csproj
src/Promitor.Integrations.Sinks.Prometheus/Promitor.Integrations.Sinks.Prometheus.csproj
src/Promitor.Integrations.Sinks.Statsd/Promitor.Integrations.Sinks.Statsd.csproj
src/Promitor.Tests.Integration/Promitor.Tests.Integration.csproj
src/Promitor.Tests.Unit/Promitor.Tests.Unit.csproj

Fixes # update .NET SDK and runtime versions to 8.0.18 across all projects

chore: update .NET SDK and runtime versions to 8.0.18 across all projects

---

src/Promitor.Integrations.AzureMonitor/AzureMonitorQueryClient.cs

fix: Use Correct ResourceId in Metric Definition Query

---

changelog/content/experimental/unreleased.md
src/Promitor.Core.Scraping/Configuration/Model/AzureMetricConfiguration.cs
src/Promitor.Tests.Unit/Core/Metrics/ScrapeDefinitionBatchPropertiesTest.cs
src/Promitor.Tests.Unit/Core/Scraping/Batching/AzureResourceDefinitionBatchingTests.cs

fix: add aggregation to batch criteria
